// ===== 本地单词库（含释义） =====
// 格式: Map<word, {meaning: string, pos: string}>
// meaning 为空表示暂无释义
const WORD_DATA = new Map([
  ['about', {meaning:'四处走动; astir.',pos:'adj.'}],
  ['above', {meaning:'天堂',pos:'n.'}],
  ['across', {meaning:'（填字游戏，通常是组合）在完成的拼图网格中水平运行的单词或...',pos:'n.'}],
  ['act', {meaning:'完成了一些事情，一张契约。',pos:'n.'}],
  ['add', {meaning:'添加的行为或实例。',pos:'n.'}],
  ['after', {meaning:'稍后；第二个（共两个） ；下一个、下一个、下一个',pos:'adj.'}],
  ['again', {meaning:'下次，再来一次。',pos:'adv.'}],
  ['age', {meaning:'一个生物（无论是动物、植物还是其他种类）存活的整个持续时间。',pos:'n.'}],
  ['ago', {meaning:'消失了；过去了；消失了；去世了；去世了。',pos:'adj.'}],
  ['agree', {meaning:'在意见、陈述或行动上协调一致；一致或和谐；团结一致……',pos:'v.'}],
  ['air', {meaning:'构成地球大气层的物质，特别是：',pos:'n.'}],
  ['all', {meaning:'（用占有代词）一个人所能做到的一切。',pos:'n.'}],
  ['allow', {meaning:'给予、给予、承认、同意、负担得起或屈服；让人拥有。',pos:'v.'}],
  ['also', {meaning:'（焦点）此外；此外；也；也。',pos:'adv.'}],
  ['always', {meaning:'在任何时候；在任何时候；从一开始。',pos:'adv.'}],
  ['among', {meaning:'表示与不同或可分离的对象混合或混合。（请参阅中的使用说明。）',pos:'prep.'}],
  ['and', {meaning:'在节奏中，分节拍的后半部分。',pos:'n.'}],
  ['angry', {meaning:'表现出或感到愤怒。',pos:'adj.'}],
  ['animal', {meaning:'在科学使用中，一种通常是移动的多细胞生物，其细胞没有被包裹...',pos:'n.'}],
  ['another', {meaning:'另一个相同类型的。',pos:'pron.'}],
  ['answer', {meaning:'回应或答复；为回应陈述或问题而说或做的事情。',pos:'n.'}],
  ['any', {meaning:'哪怕是最微不足道的程度。',pos:'adv.'}],
  ['anyone', {meaning:'任何人；任何人。',pos:'pron.'}],
  ['anything', {meaning:'某人或某件重要的事情。',pos:'n.'}],
  ['appear', {meaning:'来或在视线中；在视线中；变得可见。',pos:'v.'}],
  ['apple', {meaning:'一种常见的圆形果实，由Malus domestica树生产，在温和的气',pos:'n.'}],
  ['are', {meaning:'可接受（但已弃用且很少使用）的SI单位面积等于100平方米，或用于..',pos:'n.'}],
  ['area', {meaning:'表面范围的度量；以平方单位测量。',pos:'n.'}],
  ['arm', {meaning:'人类上肢的一部分，从肩膀到手腕，有时包括……',pos:'n.'}],
  ['around', {meaning:'（动词“to be” ）出现在附近。',pos:'adj.'}],
  ['arrive', {meaning:'到达；到达某个地方。',pos:'v.'}],
  ['art', {meaning:'有意识地产生或排列声音、颜色、形式、动作或其他元素。',pos:'n.'}],
  ['ask', {meaning:'询问的行为或实例。',pos:'n.'}],
  ['aunt', {meaning:'父母的姐妹或嫂子。',pos:'n.'}],
  ['away', {meaning:'离开；去另一个地方。',pos:'v.'}],
  ['baby', {meaning:'一个非常年轻的人，特别是从出生到几岁，或者直到步行完全成熟……',pos:'n.'}],
  ['back', {meaning:'身体的后部，特别是颈部和脊柱末端之间的部分，以及相反的部分……',pos:'n.'}],
  ['bad', {meaning:'出错了，出错了。',pos:'n.'}],
  ['bag', {meaning:'由布、纸、塑料等制成的柔性容器。',pos:'n.'}],
  ['ball', {meaning:'固体或空心球体，或大致球形的质量。',pos:'n.'}],
  ['banana', {meaning:'一种细长弯曲的热带水果，成串生长，果肉奶油状，皮肤光滑。',pos:'n.'}],
  ['band', {meaning:'用于加强或联接的材料条。',pos:'n.'}],
  ['bank', {meaning:'一个可以放置和借款并处理财务事务的机构。',pos:'n.'}],
  ['bar', {meaning:'金属或木材的坚固的、或多或少刚性的物体，其均匀的横截面小于其...',pos:'n.'}],
  ['base', {meaning:'其他事物延伸的东西；基础。',pos:'n.'}],
  ['basket', {meaning:'轻质容器，通常为圆形，顶部开口，向底部逐渐变细。',pos:'n.'}],
  ['bat', {meaning:'Chiroptera目中的任何飞行哺乳动物，通常是小型夜行性、食虫性或',pos:'n.'}],
  ['bath', {meaning:'用于洗澡的浴缸或游泳池：浴缸。',pos:'n.'}],
  ['beach', {meaning:'水体的岸边，特别是当沙质或鹅卵石状时。',pos:'n.'}],
  ['bean', {meaning:'用Java编写的可重用软件组件。',pos:'n.'}],
  ['bear', {meaning:'一种大型杂食性哺乳动物，与狗和浣熊有关，头发毛茸茸，尾巴很小，...',pos:'n.'}],
  ['beat', {meaning:'一击；一击。',pos:'n.'}],
  ['beautiful', {meaning:'一个美丽的人。可用作地址术语。',pos:'n.'}],
  ['became', {meaning:'要到达房源，请前往（某个地方）。',pos:'v.'}],
  ['because', {meaning:'出于这个原因。',pos:'adv.'}],
  ['become', {meaning:'要到达房源，请前往（某个地方）。',pos:'v.'}],
  ['bed', {meaning:'一件家具，通常是平坦柔软的，可以休息或睡觉。',pos:'n.'}],
  ['bee', {meaning:'一种飞行昆虫，属于膜翅目超级家族Apoidea中的Anthophila',pos:'n.'}],
  ['before', {meaning:'在更早的时间。',pos:'adv.'}],
  ['began', {meaning:'开始，开始或迈出第一步。',pos:'v.'}],
  ['begin', {meaning:'开始；开始。',pos:'n.'}],
  ['behind', {meaning:'后端、后端',pos:'n.'}],
  ['believe', {meaning:'接受为真实，特别是在没有绝对确定性的情况下（即与知道相反）',pos:'v.'}],
  ['bell', {meaning:'一种由金属或其他硬质材料制成的打击乐器，通常但不总是在...',pos:'n.'}],
  ['belong', {meaning:'要有合适的地方。',pos:'v.'}],
  ['below', {meaning:'在较低的地方。',pos:'adv.'}],
  ['belt', {meaning:'戴在腰间的带子将衣服固定在身体上（通常是裤子） ，拿着武器（例如...',pos:'n.'}],
  ['best', {meaning:'一个人可以做或已经做的至高无上的努力。',pos:'n.'}],
  ['better', {meaning:'一个实体，通常是动态的，被认为优于另一个实体；声称拥有优先权的人；超级',pos:'n.'}],
  ['between', {meaning:'一种短于锋利的针，带有小圆眼，用于缝制细针。',pos:'n.'}],
  ['big', {meaning:'身材高大的人或物',pos:'n.'}],
  ['bike', {meaning:'一辆车有两个轮子，一个在另一个后面，一个转向手柄，一个鞍座或座椅……',pos:'n.'}],
  ['bill', {meaning:'任何各种刀刃或尖头手枪，最初指定为盎格鲁-撒克逊剑，以及...',pos:'n.'}],
  ['bird', {meaning:'脊索动物门中的动物Aves类成员，以温血动物为特征……',pos:'n.'}],
  ['birth', {meaning:'生育的过程；生命的开始。',pos:'n.'}],
  ['birthday', {meaning:'某人出生当天的周年纪念日。',pos:'n.'}],
  ['bit', {meaning:'一块金属放置在马的嘴里，并连接到缰绳上，以引导动物。',pos:'n.'}],
  ['bite', {meaning:'叮，咬咬，叮的动作。',pos:'n.'}],
  ['black', {meaning:'在没有光线的情况下感知到的颜色/颜色，但也没有反射光线时感知到的颜色/',pos:'n.'}],
  ['blade', {meaning:'刀具、凿子或其他工具、剃须刀片/剑的锋利切削刃。',pos:'n.'}],
  ['bless', {meaning:'用宗教仪式使神圣化；使神圣。收藏。',pos:'v.'}],
  ['blind', {meaning:'窗户的遮光罩。覆盖物可以由布制成，也可以由窄板条制成。',pos:'n.'}],
  ['block', {meaning:'任何物质的大量（通常约为长方体）片段。',pos:'n.'}],
  ['blood', {meaning:'洛杉矶帮派The Bloods的成员。',pos:'n.'}],
  ['blow', {meaning:'一阵强风。',pos:'n.'}],
  ['blue', {meaning:'晴朗的天空或深海的颜色，在可见光谱中介于绿色和紫色之间，一种...',pos:'n.'}],
  ['board', {meaning:'相对较长、较宽和较薄的任何材料，通常是木材或类似材料，通常用于...',pos:'n.'}],
  ['boat', {meaning:'用于货物运输、钓鱼、赛车、休闲巡航或军事用途的船只...',pos:'n.'}],
  ['body', {meaning:'物理框架。',pos:'n.'}],
  ['boil', {meaning:'由感染引起的脓液在皮肤中的局部积聚。',pos:'n.'}],
  ['bomb', {meaning:'用作或意图用作武器的爆炸装置。',pos:'n.'}],
  ['bone', {meaning:'一种复合材料，主要由磷酸钙和胶原蛋白组成，构成骨架……',pos:'n.'}],
  ['book', {meaning:'一组捆绑在一起的纸张，在一个边缘铰链上，包含印刷或书写...',pos:'n.'}],
  ['boot', {meaning:'覆盖部分腿部的重型鞋。',pos:'n.'}],
  ['born', {meaning:'从字面上或比喻上携带或传达。',pos:'v.'}],
  ['borrow', {meaning:'滚动球的路径偏离直线;斜率;倾斜。',pos:'n.'}],
  ['boss', {meaning:'监督和指导他人工作的人；主管。',pos:'n.'}],
  ['both', {meaning:'两种中的每一种，或两种中的每一种。',pos:'pron.'}],
  ['bother', {meaning:'大惊小怪，再见。',pos:'n.'}],
  ['bottle', {meaning:'容器，通常由玻璃或塑料制成，具有锥形颈部，主要用于容纳...',pos:'n.'}],
  ['bottom', {meaning:'任何事物中最低的部分。',pos:'n.'}],
  ['bowl', {meaning:'用于盛放、混合或展示食物的大致半球形容器，如沙拉、水果或汤...',pos:'n.'}],
  ['box', {meaning:'与三维物体或空间相关的感官。',pos:'n.'}],
  ['boy', {meaning:'一个年轻的男性。',pos:'n.'}],
  ['brain', {meaning:'位于颅骨中的动物中枢神经系统的控制中心',pos:'n.'}],
  ['brake', {meaning:'蕨类植物；',pos:'n.'}],
  ['branch', {meaning:'树的木质部分从树干中生长出来，通常是分开的。',pos:'n.'}],
  ['brave', {meaning:'一位美洲原住民战士。',pos:'n.'}],
  ['bread', {meaning:'用谷物烘焙面团制成的食品。',pos:'n.'}],
  ['break', {meaning:'将某物分成两块或多块的例子。',pos:'n.'}],
  ['breakfast', {meaning:'一天中的第一顿饭，通常在早上吃。',pos:'n.'}],
  ['breath', {meaning:'呼吸的行为或过程。',pos:'n.'}],
  ['breathe', {meaning:'将空气吸入（吸入）并从肺部排出（呼出）以吸取氧气和……',pos:'v.'}],
  ['brick', {meaning:'用于建筑的硬化矩形泥土、粘土等块。',pos:'n.'}],
  ['bridge', {meaning:'跨越分水岭的构造或自然特征。',pos:'n.'}],
  ['bright', {meaning:'一位艺术家的画笔，用于油画和丙烯酸绘画，带有长长的套圈和平坦的，有点锥',pos:'n.'}],
  ['bring', {meaning:'（ ditransitive ）运送到某人/某个地方。',pos:'v.'}],
  ['broad', {meaning:'一个浅湖，是诺福克东部和萨福克众多水体之一。',pos:'n.'}],
  ['brother', {meaning:'同父异母的儿子。',pos:'n.'}],
  ['brown', {meaning:'类似于巧克力或咖啡的颜色。',pos:'n.'}],
  ['brush', {meaning:'一种由多根或多或少柔韧的刷毛或其他细丝组成的工具，附着在...',pos:'n.'}],
  ['build', {meaning:'人体的体质；人体的构成或结构。',pos:'n.'}],
  ['bunch', {meaning:'一组类似的东西，要么一起生长，要么成群结队，通常固定在……',pos:'n.'}],
  ['burn', {meaning:'由热、冷、电、辐射或腐蚀性化学物质造成的身体伤害。',pos:'n.'}],
  ['bus', {meaning:'用于在道路上运送大量人员的机动车辆。',pos:'n.'}],
  ['bush', {meaning:'一种木本植物，以其多茎和较低的高度与树木区别开来，通常是...',pos:'n.'}],
  ['business', {meaning:'特定的商业企业或机构。',pos:'n.'}],
  ['busy', {meaning:'来了一位警察。',pos:'n.'}],
  ['but', {meaning:'使用单词“but”的实例或示例。',pos:'n.'}],
  ['butter', {meaning:'通过搅拌牛奶奶油（通常是牛奶）制成的柔软的脂肪食品。',pos:'n.'}],
  ['button', {meaning:'进行调整的人，特别是保险业的就业头衔“损失理算员” （或“损失理算员”',pos:'n.'}],
  ['buy', {meaning:'被购买的东西；购买。',pos:'n.'}],
  ['cage', {meaning:'由栅栏制成的围栏，通常用于容纳动物。',pos:'n.'}],
  ['cake', {meaning:'一种丰富、甜美的甜点，通常由面粉、糖和鸡蛋制成，在烤箱中烘烤，经常……',pos:'n.'}],
  ['call', {meaning:'电话交谈',pos:'n.'}],
  ['calm', {meaning:'（在一个人身上）平静的状态；平静；没有忧虑、愤怒、恐惧或其他束缚……',pos:'n.'}],
  ['camel', {meaning:'骆驼属的一种负担兽，在沙漠地区广泛使用。',pos:'n.'}],
  ['camera', {meaning:'用于拍摄静止或运动图片或照片的设备。',pos:'n.'}],
  ['camp', {meaning:'在帐篷或其他临时结构中充当临时住所的户外场所。',pos:'n.'}],
  ['can', {meaning:'（辅助动词，有缺陷）知道如何去做；能够去做。',pos:'v.'}],
  ['candle', {meaning:'A light source consisting of a wick embedded in a solid, flammable substance such as wax, tallow,...',pos:'n.'}],
  ['candy', {meaning:'Edible, sweet-tasting confectionery containing sugar, or sometimes artificial sweeteners, and oft...',pos:'n.'}],
  ['cap', {meaning:'A close-fitting hat, either brimless or peaked.',pos:'n.'}],
  ['captain', {meaning:'A chief or leader.',pos:'n.'}],
  ['car', {meaning:'A wheeled vehicle that moves independently, with at least three wheels, powered mechanically, ste...',pos:'n.'}],
  ['card', {meaning:'A playing card.',pos:'n.'}],
  ['care', {meaning:'Grief, sorrow.',pos:'n.'}],
  ['careful', {meaning:'Taking care; attentive to potential danger, error or harm; cautious.',pos:'adj.'}],
  ['careless', {meaning:'Not concerned or worried (about).',pos:'adj.'}],
  ['carry', {meaning:'A manner of transporting or lifting something; the grip or position in which something is carried.',pos:'n.'}],
  ['case', {meaning:'An actual event, situation, or fact.',pos:'n.'}],
  ['castle', {meaning:'A large building that is fortified and contains many defences; in previous ages often inhabited b...',pos:'n.'}],
  ['cat', {meaning:'An animal of the family Felidae:',pos:'n.'}],
  ['catch', {meaning:'The act of seizing or capturing.',pos:'n.'}],
  ['cattle', {meaning:'Domesticated bovine animals (cows, bulls, steers etc).',pos:'n.'}],
  ['cause', {meaning:'(often with of, typically of adverse results) The source of, or reason for, an event or action; t...',pos:'n.'}],
  ['cave', {meaning:'A large, naturally-occurring cavity formed underground or in the face of a cliff or a hillside.',pos:'n.'}],
  ['celebrate', {meaning:'To extol or honour in a solemn manner.',pos:'v.'}],
  ['cent', {meaning:'(money) A subunit of currency equal to one-hundredth of the main unit of currency in many countri...',pos:'n.'}],
  ['center', {meaning:'The point in the interior of a circle that is equidistant from all points on the circumference.',pos:'n.'}],
  ['century', {meaning:'A period of 100 consecutive years; often specifically a numbered period with conventional start a...',pos:'n.'}],
  ['cereal', {meaning:'A type of grass (such as wheat, rice or oats) cultivated for its edible grains.',pos:'n.'}],
  ['certain', {meaning:'(with "the") Something certain.',pos:'n.'}],
  ['chair', {meaning:'An item of furniture used to sit on or in, comprising a seat, legs, back, and sometimes arm rests...',pos:'n.'}],
  ['chalk', {meaning:'A soft, white, powdery limestone.',pos:'n.'}],
  ['champion', {meaning:'An ongoing winner in a game or contest.',pos:'n.'}],
  ['chance', {meaning:'An opportunity or possibility.',pos:'n.'}],
  ['change', {meaning:'The process of becoming different.',pos:'n.'}],
  ['channel', {meaning:'The physical confine of a river or slough, consisting of a bed and banks.',pos:'n.'}],
  ['chapter', {meaning:'(authorship) One of the main sections into which the text of a book is divided.',pos:'n.'}],
  ['charge', {meaning:'The amount of money levied for a service.',pos:'n.'}],
  ['chase', {meaning:'The act of one who chases another; a pursuit.',pos:'n.'}],
  ['chat', {meaning:'Informal conversation.',pos:'n.'}],
  ['cheap', {meaning:'Trade; traffic; chaffer; chaffering.',pos:'n.'}],
  ['cheat', {meaning:'To violate rules in order to gain advantage from a situation.',pos:'v.'}],
  ['check', {meaning:'A situation in which the king is directly threatened by an opposing piece.',pos:'n.'}],
  ['cheek', {meaning:'The soft skin on each side of the face, below the eyes; the outer surface of the sides of the ora...',pos:'n.'}],
  ['cheer', {meaning:'A cheerful attitude; happiness; a good, happy, or positive mood.',pos:'n.'}],
  ['cheese', {meaning:'A dairy product made from curdled or cultured milk.',pos:'n.'}],
  ['cherry', {meaning:'A small fruit, usually red, black or yellow, with a smooth hard seed and a short hard stem.',pos:'n.'}],
  ['chest', {meaning:'A box, now usually a large strong box with a secure convex lid.',pos:'n.'}],
  ['chicken', {meaning:'A domestic fowl, Gallus gallus, especially when young.',pos:'n.'}],
  ['chief', {meaning:'A leader or head of a group of people, organisation, etc.',pos:'n.'}],
  ['child', {meaning:'A person who has not yet reached adulthood, whether natural (puberty), cultural (initiation), or ...',pos:'n.'}],
  ['children', {meaning:'A person who has not yet reached adulthood, whether natural (puberty), cultural (initiation), or ...',pos:'n.'}],
  ['chocolate', {meaning:'A food made from ground roasted cocoa beans.',pos:'n.'}],
  ['choice', {meaning:'An option; a decision; an opportunity to choose or select something.',pos:'n.'}],
  ['choose', {meaning:'To pick; to make the choice of; to select.',pos:'v.'}],
  ['chop', {meaning:'A cut of meat, often containing a section of a rib.',pos:'n.'}],
  ['church', {meaning:'A Christian house of worship; a building where Christian religious services take place.',pos:'n.'}],
  ['circle', {meaning:'A two-dimensional geometric figure, a line, consisting of the set of all those points in a plane ...',pos:'n.'}],
  ['citizen', {meaning:'A resident of a city or town, especially one with legally-recognized rights or duties.',pos:'n.'}],
  ['city', {meaning:'A large settlement, bigger than a town; sometimes with a specific legal definition, depending on ...',pos:'n.'}],
  ['claim', {meaning:'A demand of ownership made for something.',pos:'n.'}],
  ['class', {meaning:'A group, collection, category or set sharing characteristics or attributes.',pos:'n.'}],
  ['classmate', {meaning:'A student who is in the same class at school.',pos:'n.'}],
  ['claw', {meaning:'A curved, pointed horny nail on each digit of the foot of a mammal, reptile, or bird.',pos:'n.'}],
  ['clay', {meaning:'A mineral substance made up of small crystals of silica and alumina, that is ductile when moist; ...',pos:'n.'}],
  ['clean', {meaning:'Removal of dirt.',pos:'n.'}],
  ['clear', {meaning:'Full extent; distance between extreme limits; especially; the distance between the nearest surfac...',pos:'n.'}],
]);

module.exports = { WORD_DATA };
