// ===== 本地单词库（含中文释义） =====
// 格式: Map<word, {meaning: string, pos: string}>
// 数据来源: ECDICT 开源英汉词典 + 牛津3000核心词/中高考词库
const WORD_DATA = new Map([
  ['about', {meaning:'在...周围',pos:'adj.'}],
  ['above', {meaning:'在上方',pos:'n.'}],
  ['across', {meaning:'越过',pos:'n.'}],
  ['act', {meaning:'行动',pos:'n.'}],
  ['add', {meaning:'增加',pos:'n.'}],
  ['after', {meaning:'在...之后',pos:'adj.'}],
  ['again', {meaning:'再一次',pos:'adv.'}],
  ['age', {meaning:'年龄',pos:'n.'}],
  ['ago', {meaning:'以前',pos:'adj.'}],
  ['agree', {meaning:'同意',pos:'v.'}],
  ['air', {meaning:'空气',pos:'n.'}],
  ['all', {meaning:'所有的',pos:'n.'}],
  ['allow', {meaning:'允许',pos:'v.'}],
  ['also', {meaning:'也',pos:'adv.'}],
  ['always', {meaning:'总是',pos:'adv.'}],
  ['among', {meaning:'在...之中',pos:'prep.'}],
  ['and', {meaning:'和',pos:'n.'}],
  ['angry', {meaning:'生气的',pos:'adj.'}],
  ['animal', {meaning:'动物',pos:'n.'}],
  ['another', {meaning:'另外的',pos:'pron.'}],
  ['answer', {meaning:'答案',pos:'n.'}],
  ['any', {meaning:'任何的',pos:'adv.'}],
  ['anyone', {meaning:'任何人',pos:'pron.'}],
  ['anything', {meaning:'任何事',pos:'n.'}],
  ['appear', {meaning:'出现',pos:'v.'}],
  ['apple', {meaning:'苹果',pos:'n.'}],
  ['are', {meaning:'be的现在时复数或第二人称单数',pos:'n.'}],
  ['area', {meaning:'区域',pos:'n.'}],
  ['arm', {meaning:'手臂',pos:'n.'}],
  ['around', {meaning:'包围',pos:'adj.'}],
  ['arrive', {meaning:'到达',pos:'v.'}],
  ['art', {meaning:'艺术',pos:'n.'}],
  ['ask', {meaning:'问',pos:'n.'}],
  ['aunt', {meaning:'阿姨',pos:'n.'}],
  ['away', {meaning:'离去',pos:'v.'}],
  ['baby', {meaning:'婴孩',pos:'n.'}],
  ['back', {meaning:'后面的',pos:'n.'}],
  ['bad', {meaning:'坏的',pos:'n.'}],
  ['bag', {meaning:'袋子',pos:'n.'}],
  ['ball', {meaning:'球',pos:'n.'}],
  ['banana', {meaning:'香蕉',pos:'n.'}],
  ['band', {meaning:'带子',pos:'n.'}],
  ['bank', {meaning:'银行',pos:'n.'}],
  ['bar', {meaning:'条',pos:'n.'}],
  ['base', {meaning:'底部',pos:'n.'}],
  ['basket', {meaning:'篮',pos:'n.'}],
  ['bat', {meaning:'蝙蝠',pos:'n.'}],
  ['bath', {meaning:'沐浴',pos:'n.'}],
  ['beach', {meaning:'海滩',pos:'n.'}],
  ['bean', {meaning:'豆子',pos:'n.'}],
  ['bear', {meaning:'熊',pos:'n.'}],
  ['beat', {meaning:'心跳(声)',pos:'n.'}],
  ['beautiful', {meaning:'美丽的',pos:'n.'}],
  ['became', {meaning:'become的过去式',pos:'v.'}],
  ['because', {meaning:'因为',pos:'adv.'}],
  ['become', {meaning:'变成',pos:'v.'}],
  ['bed', {meaning:'床',pos:'n.'}],
  ['bee', {meaning:'蜜蜂',pos:'n.'}],
  ['before', {meaning:'在...之前',pos:'adv.'}],
  ['began', {meaning:'begin的过去式',pos:'v.'}],
  ['begin', {meaning:'开始',pos:'n.'}],
  ['behind', {meaning:'在后地',pos:'n.'}],
  ['believe', {meaning:'相信',pos:'v.'}],
  ['bell', {meaning:'铃',pos:'n.'}],
  ['belong', {meaning:'属于',pos:'v.'}],
  ['below', {meaning:'在下面',pos:'adv.'}],
  ['belt', {meaning:'带子',pos:'n.'}],
  ['best', {meaning:'最好的',pos:'n.'}],
  ['better', {meaning:'较好的',pos:'n.'}],
  ['between', {meaning:'在...之间',pos:'n.'}],
  ['big', {meaning:'大的',pos:'n.'}],
  ['bike', {meaning:'自行车',pos:'n.'}],
  ['bill', {meaning:'帐单',pos:'n.'}],
  ['bird', {meaning:'鸟',pos:'n.'}],
  ['birth', {meaning:'出生',pos:'n.'}],
  ['birthday', {meaning:'生日',pos:'n.'}],
  ['bit', {meaning:'少量',pos:'n.'}],
  ['bite', {meaning:'咬',pos:'n.'}],
  ['black', {meaning:'黑色',pos:'n.'}],
  ['blade', {meaning:'叶片',pos:'n.'}],
  ['bless', {meaning:'祝福',pos:'v.'}],
  ['blind', {meaning:'蒙蔽物',pos:'n.'}],
  ['block', {meaning:'街区',pos:'n.'}],
  ['blood', {meaning:'血',pos:'n.'}],
  ['blow', {meaning:'吹',pos:'n.'}],
  ['blue', {meaning:'蓝色',pos:'n.'}],
  ['board', {meaning:'木板',pos:'n.'}],
  ['boat', {meaning:'船',pos:'n.'}],
  ['body', {meaning:'身体',pos:'n.'}],
  ['boil', {meaning:'煮沸',pos:'n.'}],
  ['bomb', {meaning:'炸弹',pos:'n.'}],
  ['bone', {meaning:'骨头',pos:'n.'}],
  ['book', {meaning:'书',pos:'n.'}],
  ['boot', {meaning:'长靴',pos:'n.'}],
  ['born', {meaning:'天生的',pos:'v.'}],
  ['borrow', {meaning:'借',pos:'n.'}],
  ['boss', {meaning:'老板',pos:'n.'}],
  ['both', {meaning:'两者的',pos:'pron.'}],
  ['bother', {meaning:'烦扰',pos:'n.'}],
  ['bottle', {meaning:'瓶子',pos:'n.'}],
  ['bottom', {meaning:'底部',pos:'n.'}],
  ['bowl', {meaning:'碗',pos:'n.'}],
  ['box', {meaning:'盒子',pos:'n.'}],
  ['boy', {meaning:'男孩',pos:'n.'}],
  ['brain', {meaning:'脑',pos:'n.'}],
  ['brake', {meaning:'刹车',pos:'n.'}],
  ['branch', {meaning:'树枝',pos:'n.'}],
  ['brave', {meaning:'勇敢的',pos:'n.'}],
  ['bread', {meaning:'面包',pos:'n.'}],
  ['break', {meaning:'休息',pos:'n.'}],
  ['breakfast', {meaning:'早餐',pos:'n.'}],
  ['breath', {meaning:'呼吸',pos:'n.'}],
  ['breathe', {meaning:'呼吸',pos:'v.'}],
  ['brick', {meaning:'砖块',pos:'n.'}],
  ['bridge', {meaning:'桥',pos:'n.'}],
  ['bright', {meaning:'明亮的',pos:'n.'}],
  ['bring', {meaning:'带来',pos:'v.'}],
  ['broad', {meaning:'宽广的',pos:'n.'}],
  ['brother', {meaning:'兄弟',pos:'n.'}],
  ['brown', {meaning:'褐色',pos:'n.'}],
  ['brush', {meaning:'刷子',pos:'n.'}],
  ['build', {meaning:'建立',pos:'n.'}],
  ['bunch', {meaning:'串',pos:'n.'}],
  ['burn', {meaning:'烧',pos:'n.'}],
  ['bus', {meaning:'公共汽车',pos:'n.'}],
  ['bush', {meaning:'矮树丛',pos:'n.'}],
  ['business', {meaning:'生意',pos:'n.'}],
  ['busy', {meaning:'忙碌的',pos:'n.'}],
  ['but', {meaning:'除了',pos:'n.'}],
  ['butter', {meaning:'奶油',pos:'n.'}],
  ['button', {meaning:'钮扣',pos:'n.'}],
  ['buy', {meaning:'买',pos:'n.'}],
  ['cage', {meaning:'笼',pos:'n.'}],
  ['cake', {meaning:'蛋糕',pos:'n.'}],
  ['call', {meaning:'呼叫',pos:'n.'}],
  ['calm', {meaning:'平稳',pos:'n.'}],
  ['camel', {meaning:'骆驼',pos:'n.'}],
  ['camera', {meaning:'照相机',pos:'n.'}],
  ['camp', {meaning:'露营',pos:'n.'}],
  ['can', {meaning:'装罐',pos:'v.'}],
  ['candle', {meaning:'蜡烛',pos:'n.'}],
  ['candy', {meaning:'糖果',pos:'n.'}],
  ['cap', {meaning:'盖子',pos:'n.'}],
  ['captain', {meaning:'船长',pos:'n.'}],
  ['car', {meaning:'汽车',pos:'n.'}],
  ['card', {meaning:'卡片',pos:'n.'}],
  ['care', {meaning:'小心',pos:'n.'}],
  ['careful', {meaning:'小心的',pos:'adj.'}],
  ['careless', {meaning:'粗心的',pos:'adj.'}],
  ['carry', {meaning:'进位',pos:'n.'}],
  ['case', {meaning:'情形',pos:'n.'}],
  ['castle', {meaning:'城堡',pos:'n.'}],
  ['cat', {meaning:'猫',pos:'n.'}],
  ['catch', {meaning:'捕捉',pos:'n.'}],
  ['cattle', {meaning:'牛',pos:'n.'}],
  ['cause', {meaning:'原因',pos:'n.'}],
  ['cave', {meaning:'洞',pos:'n.'}],
  ['celebrate', {meaning:'庆祝',pos:'v.'}],
  ['cent', {meaning:'分',pos:'n.'}],
  ['center', {meaning:'中心',pos:'n.'}],
  ['century', {meaning:'世纪',pos:'n.'}],
  ['cereal', {meaning:'谷类食品',pos:'n.'}],
  ['certain', {meaning:'确定的',pos:'n.'}],
  ['chair', {meaning:'椅子',pos:'n.'}],
  ['chalk', {meaning:'粉笔',pos:'n.'}],
  ['champion', {meaning:'冠军',pos:'n.'}],
  ['chance', {meaning:'机会',pos:'n.'}],
  ['change', {meaning:'变化',pos:'n.'}],
  ['channel', {meaning:'海峡',pos:'n.'}],
  ['chapter', {meaning:'章',pos:'n.'}],
  ['charge', {meaning:'指控',pos:'n.'}],
  ['chase', {meaning:'追求',pos:'n.'}],
  ['chat', {meaning:'闲谈',pos:'n.'}],
  ['cheap', {meaning:'便宜的',pos:'n.'}],
  ['cheat', {meaning:'欺骗',pos:'v.'}],
  ['check', {meaning:'检查',pos:'n.'}],
  ['cheek', {meaning:'颊',pos:'n.'}],
  ['cheer', {meaning:'愉快',pos:'n.'}],
  ['cheese', {meaning:'乳酪',pos:'n.'}],
  ['cherry', {meaning:'樱桃',pos:'n.'}],
  ['chest', {meaning:'胸',pos:'n.'}],
  ['chicken', {meaning:'小鸡',pos:'n.'}],
  ['chief', {meaning:'领袖',pos:'n.'}],
  ['child', {meaning:'孩子',pos:'n.'}],
  ['children', {meaning:'孩子',pos:'n.'}],
  ['chocolate', {meaning:'巧克力',pos:'n.'}],
  ['choice', {meaning:'选择',pos:'n.'}],
  ['choose', {meaning:'选择',pos:'v.'}],
  ['chop', {meaning:'肋条肉',pos:'n.'}],
  ['church', {meaning:'教堂',pos:'n.'}],
  ['circle', {meaning:'圆周',pos:'n.'}],
  ['citizen', {meaning:'市民',pos:'n.'}],
  ['city', {meaning:'城市',pos:'n.'}],
  ['claim', {meaning:'要求',pos:'n.'}],
  ['class', {meaning:'班级',pos:'n.'}],
  ['classmate', {meaning:'同班同学',pos:'n.'}],
  ['claw', {meaning:'爪',pos:'n.'}],
  ['clay', {meaning:'泥土',pos:'n.'}],
  ['clean', {meaning:'干净的',pos:'n.'}],
  ['clear', {meaning:'清楚的',pos:'n.'}],
  ['ability', {meaning:'能力',pos:'n.'}],
  ['able', {meaning:'能干的',pos:'n.'}],
  ['abs', {meaning:'绝对',pos:'n.'}],
  ['abuse', {meaning:'滥用',pos:'n.'}],
  ['accept', {meaning:'接受',pos:'n.'}],
  ['access', {meaning:'通路',pos:'n.'}],
  ['account', {meaning:'报告',pos:'n.'}],
  ['accuse', {meaning:'指责',pos:'n.'}],
  ['ace', {meaning:'幺点',pos:'n.'}],
  ['acid', {meaning:'酸',pos:'n.'}],
  ['action', {meaning:'行动',pos:'n.'}],
  ['active', {meaning:'活跃的',pos:'n.'}],
  ['activity', {meaning:'活动',pos:'n.'}],
  ['actor', {meaning:'男演员',pos:'n.'}],
  ['actually', {meaning:'事实上',pos:'n.'}],
  ['adapt', {meaning:'使适应',pos:'n.'}],
  ['admit', {meaning:'承认',pos:'n.'}],
  ['adopt', {meaning:'采用',pos:'n.'}],
  ['adult', {meaning:'成人',pos:'n.'}],
  ['advice', {meaning:'忠告',pos:'n.'}],
  ['affair', {meaning:'事件',pos:'n.'}],
  ['affect', {meaning:'影响',pos:'n.'}],
  ['afraid', {meaning:'害怕的',pos:'n.'}],
  ['against', {meaning:'反对',pos:'n.'}],
  ['aged', {meaning:'老的',pos:'n.'}],
  ['agency', {meaning:'代理机构',pos:'n.'}],
  ['agent', {meaning:'代理商',pos:'n.'}],
  ['ahead', {meaning:'领先的',pos:'n.'}],
  ['aid', {meaning:'帮助',pos:'n.'}],
  ['aids', {meaning:'爱滋病(获得性免疫缺陷综合征)\n高级综合数据系统',pos:'n.'}],
  ['aim', {meaning:'目标',pos:'n.'}],
  ['alarm', {meaning:'惊恐',pos:'n.'}],
  ['ale', {meaning:'麦芽酒\n麦芽酒',pos:'n.'}],
  ['alive', {meaning:'活着的',pos:'n.'}],
  ['ally', {meaning:'同盟者',pos:'n.'}],
  ['almost', {meaning:'几乎',pos:'n.'}],
  ['alone', {meaning:'孤独的',pos:'n.'}],
  ['along', {meaning:'平行地',pos:'n.'}],
  ['already', {meaning:'已经',pos:'n.'}],
  ['alter', {meaning:'改变',pos:'n.'}],
  ['although', {meaning:'虽然',pos:'n.'}],
  ['amid', {meaning:'在其间',pos:'n.'}],
  ['amount', {meaning:'总数',pos:'n.'}],
  ['anger', {meaning:'忿怒\nvt. 激怒',pos:'n.'}],
  ['angle', {meaning:'角',pos:'n.'}],
  ['ankle', {meaning:'踝\n踝',pos:'n.'}],
  ['announce', {meaning:'宣布',pos:'n.'}],
  ['annual', {meaning:'年刊',pos:'n.'}],
  ['ant', {meaning:'蚂蚁',pos:'n.'}],
  ['anyway', {meaning:'无论如何',pos:'n.'}],
  ['apart', {meaning:'成零碎',pos:'n.'}],
  ['ape', {meaning:'无尾猿\n应用程序评价',pos:'n.'}],
  ['appeal', {meaning:'恳求',pos:'n.'}],
  ['apply', {meaning:'涂',pos:'n.'}],
  ['approach', {meaning:'接近',pos:'n.'}],
  ['apr', {meaning:'替换通路再试器',pos:'n.'}],
  ['apt', {meaning:'有...倾向的',pos:'n.'}],
  ['arc', {meaning:'弧',pos:'n.'}],
  ['argue', {meaning:'提出理由',pos:'n.'}],
  ['arise', {meaning:'站立',pos:'n.'}],
  ['armed', {meaning:'有扶手的',pos:'n.'}],
  ['arms', {meaning:'武器',pos:'n.'}],
  ['army', {meaning:'军队',pos:'n.'}],
  ['arrest', {meaning:'逮捕',pos:'n.'}],
  ['article', {meaning:'文章',pos:'n.'}],
  ['artist', {meaning:'艺术家',pos:'n.'}],
  ['ash', {meaning:'灰',pos:'n.'}],
  ['aside', {meaning:'小声说的话',pos:'n.'}],
  ['aspect', {meaning:'外观',pos:'n.'}],
  ['ass', {meaning:'驴',pos:'n.'}],
  ['assume', {meaning:'假定',pos:'n.'}],
  ['atom', {meaning:'原子',pos:'n.'}],
  ['attack', {meaning:'攻击',pos:'n.'}],
  ['attempt', {meaning:'尝试',pos:'n.'}],
  ['attend', {meaning:'参加',pos:'n.'}],
  ['attention', {meaning:'注意',pos:'n.'}],
  ['author', {meaning:'作家',pos:'n.'}],
  ['authority', {meaning:'权力',pos:'n.'}],
  ['auto', {meaning:'汽车\npref. 表示自己、本身',pos:'n.'}],
  ['available', {meaning:'可利用的',pos:'n.'}],
  ['avoid', {meaning:'避免',pos:'n.'}],
  ['awake', {meaning:'醒着的\nvt. 唤醒',pos:'n.'}],
  ['award', {meaning:'奖品',pos:'n.'}],
  ['aware', {meaning:'知道的',pos:'n.'}],
  ['awe', {meaning:'敬畏\nvt. 使敬畏',pos:'n.'}],
  ['awful', {meaning:'可怕的',pos:'n.'}],
  ['axe', {meaning:'斧',pos:'n.'}],
  ['aye', {meaning:'赞成票',pos:'n.'}],
  ['badly', {meaning:'严重地',pos:'n.'}],
  ['bake', {meaning:'烘焙',pos:'n.'}],
  ['ban', {meaning:'禁令\nvt. 禁止',pos:'n.'}],
  ['bare', {meaning:'赤裸的',pos:'n.'}],
  ['basic', {meaning:'基本原理',pos:'n.'}],
  ['basis', {meaning:'基础',pos:'n.'}],
  ['battle', {meaning:'战役\nv. 战斗',pos:'n.'}],
  ['bay', {meaning:'海湾',pos:'n.'}],
  ['beak', {meaning:'鸟嘴',pos:'n.'}],
  ['beard', {meaning:'胡须\nvt. 抓住胡须',pos:'n.'}],
  ['beef', {meaning:'牛肉',pos:'n.'}],
  ['beer', {meaning:'啤酒\n啤酒',pos:'n.'}],
  ['beg', {meaning:'乞求',pos:'n.'}],
  ['belief', {meaning:'信念',pos:'n.'}],
  ['bend', {meaning:'变弯曲',pos:'n.'}],
  ['benefit', {meaning:'利益\nvt. 有益于\nvi. 受益',pos:'n.'}],
  ['bent', {meaning:'弯曲的',pos:'n.'}],
  ['bet', {meaning:'打赌',pos:'n.'}],
  ['beyond', {meaning:'超过',pos:'n.'}],
  ['bid', {meaning:'出价\nv. 命令',pos:'n.'}],
  ['bin', {meaning:'(贮存谷物等的)容器',pos:'n.'}],
  ['blame', {meaning:'过失',pos:'n.'}],
  ['blank', {meaning:'空格',pos:'n.'}],
  ['bob', {meaning:'剪短',pos:'n.'}],
  ['bog', {meaning:'沼泽\nvt. 使陷于泥沼\nvi. 陷于泥沼',pos:'n.'}],
  ['bond', {meaning:'捆绑物',pos:'n.'}],
  ['boo', {meaning:'嘘(某人)',pos:'n.'}],
  ['boom', {meaning:'繁荣',pos:'n.'}],
  ['border', {meaning:'边缘',pos:'n.'}],
  ['bore', {meaning:'令人讨厌的人',pos:'n.'}],
  ['bound', {meaning:'跃',pos:'n.'}],
  ['bow', {meaning:'弓',pos:'n.'}],
  ['bra', {meaning:'奶罩\n左矢',pos:'n.'}],
  ['brand', {meaning:'商标',pos:'n.'}],
  ['breed', {meaning:'种类',pos:'n.'}],
  ['brief', {meaning:'摘要',pos:'n.'}],
  ['bud', {meaning:'芽',pos:'n.'}],
  ['budget', {meaning:'预算\nvi. 编预算\nvt. 编入预算',pos:'n.'}],
  ['bug', {meaning:'错误',pos:'n.'}],
  ['building', {meaning:'建筑物',pos:'n.'}],
  ['bum', {meaning:'游荡者',pos:'n.'}],
  ['bun', {meaning:'小面包\n血液尿素氮',pos:'n.'}],
  ['burst', {meaning:'破裂',pos:'n.'}],
  ['bury', {meaning:'埋葬',pos:'n.'}],
  ['bye', {meaning:'再会',pos:'n.'}],
  ['cab', {meaning:'出租车',pos:'n.'}],
  ['cable', {meaning:'电缆',pos:'n.'}],
  ['campaign', {meaning:'战役',pos:'n.'}],
  ['cancer', {meaning:'癌',pos:'n.'}],
  ['capital', {meaning:'首都',pos:'n.'}],
  ['career', {meaning:'事业',pos:'n.'}],
  ['cash', {meaning:'现金\nvt. 兑现',pos:'n.'}],
  ['cast', {meaning:'演员阵容',pos:'n.'}],
  ['cease', {meaning:'停止\nv. 停止',pos:'n.'}],
  ['cell', {meaning:'单元',pos:'n.'}],
  ['central', {meaning:'中央的',pos:'n.'}],
  ['ceo', {meaning:'首席执行官；执行总裁（chief executive officer）',pos:'n.'}],
  ['certainly', {meaning:'确定地',pos:'n.'}],
  ['chain', {meaning:'链',pos:'n.'}],
  ['character', {meaning:'个性',pos:'n.'}],
  ['chart', {meaning:'图表',pos:'n.'}],
  ['chew', {meaning:'咀嚼',pos:'n.'}],
  ['chin', {meaning:'下巴',pos:'n.'}],
  ['chip', {meaning:'屑片',pos:'n.'}],
  ['cite', {meaning:'引用',pos:'n.'}],
  ['civil', {meaning:'市民的',pos:'n.'}],
  ['clap', {meaning:'拍手',pos:'n.'}],
  ['clerk', {meaning:'办事员',pos:'n.'}],
  ['click', {meaning:'咔哒声',pos:'n.'}],
  ['client', {meaning:'客户',pos:'n.'}],
  ['climb', {meaning:'攀登',pos:'n.'}],
  ['clock', {meaning:'时钟',pos:'n.'}],
  ['close', {meaning:'结束',pos:'n.'}],
  ['cloth', {meaning:'布料',pos:'n.'}],
  ['cloud', {meaning:'云',pos:'n.'}],
  ['club', {meaning:'俱乐部',pos:'n.'}],
  ['coach', {meaning:'四轮大马车',pos:'n.'}],
  ['coal', {meaning:'煤',pos:'n.'}],
  ['coast', {meaning:'海岸',pos:'n.'}],
  ['coat', {meaning:'外套\nvt. 外面覆盖',pos:'n.'}],
  ['cod', {meaning:'鳕',pos:'n.'}],
  ['code', {meaning:'代码',pos:'n.'}],
  ['coffee', {meaning:'咖啡',pos:'n.'}],
  ['coin', {meaning:'硬币',pos:'n.'}],
  ['cold', {meaning:'感冒',pos:'n.'}],
  ['college', {meaning:'学院',pos:'n.'}],
  ['come', {meaning:'过来',pos:'n.'}],
  ['commit', {meaning:'委托(托付)',pos:'n.'}],
  ['committee', {meaning:'委员会\n委员会',pos:'n.'}],
  ['community', {meaning:'社区',pos:'n.'}],
  ['company', {meaning:'公司',pos:'n.'}],
  ['complete', {meaning:'完全的',pos:'n.'}],
  ['computer', {meaning:'电脑',pos:'n.'}],
  ['con', {meaning:'精读',pos:'n.'}],
  ['concern', {meaning:'关心',pos:'n.'}],
  ['condition', {meaning:'情况',pos:'n.'}],
  ['consider', {meaning:'考虑',pos:'n.'}],
  ['continue', {meaning:'继续',pos:'n.'}],
  ['control', {meaning:'控制',pos:'n.'}],
  ['cook', {meaning:'厨子',pos:'n.'}],
  ['cool', {meaning:'凉爽',pos:'n.'}],
  ['cop', {meaning:'警官\nvt. 抓住',pos:'n.'}],
  ['cope', {meaning:'竞争',pos:'n.'}],
  ['copy', {meaning:'副本',pos:'n.'}],
  ['core', {meaning:'核心',pos:'n.'}],
  ['corner', {meaning:'角落',pos:'n.'}],
  ['cost', {meaning:'代价',pos:'n.'}],
  ['cot', {meaning:'行军床',pos:'n.'}],
  ['cough', {meaning:'咳嗽\nvi. 咳嗽\nvt. 咳出',pos:'n.'}],
  ['could', {meaning:'aux. 可以',pos:'n.'}],
  ['council', {meaning:'会议',pos:'n.'}],
  ['country', {meaning:'国家',pos:'n.'}],
  ['county', {meaning:'县',pos:'n.'}],
  ['coup', {meaning:'砰然的一击',pos:'n.'}],
  ['couple', {meaning:'对',pos:'n.'}],
  ['course', {meaning:'课程',pos:'n.'}],
  ['court', {meaning:'法院',pos:'n.'}],
  ['cousin', {meaning:'堂兄弟姊妹',pos:'n.'}],
  ['cover', {meaning:'盖子',pos:'n.'}],
  ['cow', {meaning:'母牛',pos:'n.'}],
  ['crack', {meaning:'裂缝',pos:'n.'}],
  ['craft', {meaning:'技艺',pos:'n.'}],
  ['crash', {meaning:'哗啦声',pos:'n.'}],
  ['crazy', {meaning:'发狂的',pos:'n.'}],
  ['cream', {meaning:'乳酪',pos:'n.'}],
  ['create', {meaning:'创造',pos:'n.'}],
  ['credit', {meaning:'信用',pos:'n.'}],
  ['crew', {meaning:'全体人员',pos:'n.'}],
  ['crime', {meaning:'犯罪',pos:'n.'}],
  ['crisis', {meaning:'危机',pos:'n.'}],
  ['crop', {meaning:'农作物',pos:'n.'}],
  ['cross', {meaning:'十字架',pos:'n.'}],
  ['crowd', {meaning:'群众',pos:'n.'}],
  ['crown', {meaning:'王冠',pos:'n.'}],
  ['crush', {meaning:'压碎',pos:'n.'}],
  ['cry', {meaning:'叫声',pos:'n.'}],
  ['cub', {meaning:'幼兽',pos:'n.'}],
  ['cue', {meaning:'提示',pos:'n.'}],
  ['culture', {meaning:'文化',pos:'n.'}],
  ['cup', {meaning:'杯子',pos:'n.'}],
  ['curb', {meaning:'抑制',pos:'n.'}],
  ['cure', {meaning:'治疗',pos:'n.'}],
  ['curl', {meaning:'拳曲',pos:'n.'}],
  ['current', {meaning:'涌流',pos:'n.'}],
  ['curve', {meaning:'曲线',pos:'n.'}],
  ['cut', {meaning:'切口',pos:'n.'}],
  ['cycle', {meaning:'周期',pos:'n.'}],
  ['dab', {meaning:'少量',pos:'n.'}],
  ['dad', {meaning:'爸爸',pos:'n.'}],
  ['daily', {meaning:'每日的',pos:'n.'}],
  ['dam', {meaning:'水坝',pos:'n.'}],
  ['damage', {meaning:'损害',pos:'n.'}],
  ['damp', {meaning:'潮湿',pos:'n.'}],
  ['dance', {meaning:'跳舞',pos:'n.'}],
  ['danger', {meaning:'危险',pos:'n.'}],
  ['dare', {meaning:'挑战',pos:'n.'}],
  ['dark', {meaning:'黑暗',pos:'n.'}],
  ['data', {meaning:'资料',pos:'n.'}],
  ['date', {meaning:'日期',pos:'n.'}],
  ['daughter', {meaning:'女儿\na. 女儿的',pos:'n.'}],
  ['day', {meaning:'天',pos:'n.'}],
  ['dead', {meaning:'死的',pos:'n.'}],
  ['deaf', {meaning:'聋的\n聋的',pos:'n.'}],
  ['deal', {meaning:'交易',pos:'n.'}],
  ['dear', {meaning:'亲爱的人\na. 亲爱的',pos:'n.'}],
  ['death', {meaning:'死亡\n死亡',pos:'n.'}],
  ['debate', {meaning:'辩论',pos:'n.'}],
  ['debt', {meaning:'债务',pos:'n.'}],
  ['decade', {meaning:'十年',pos:'n.'}],
  ['decide', {meaning:'决定',pos:'n.'}],
  ['decision', {meaning:'决定',pos:'n.'}],
  ['deck', {meaning:'甲板',pos:'n.'}],
  ['deep', {meaning:'深的\nadv. 深入地\nn. 深渊',pos:'n.'}],
  ['defeat', {meaning:'败北',pos:'n.'}],
  ['defend', {meaning:'防护',pos:'n.'}],
  ['define', {meaning:'定义',pos:'n.'}],
  ['degree', {meaning:'程度',pos:'n.'}],
  ['delay', {meaning:'耽搁',pos:'n.'}],
  ['demand', {meaning:'要求',pos:'n.'}],
  ['den', {meaning:'兽穴',pos:'n.'}],
  ['deny', {meaning:'否认',pos:'n.'}],
  ['depend', {meaning:'靠',pos:'n.'}],
  ['depth', {meaning:'深度',pos:'n.'}],
  ['describe', {meaning:'描述',pos:'n.'}],
  ['design', {meaning:'设计',pos:'n.'}],
  ['desire', {meaning:'欲望',pos:'n.'}],
  ['desk', {meaning:'书桌',pos:'n.'}],
  ['despite', {meaning:'轻视',pos:'n.'}],
  ['detail', {meaning:'细节',pos:'n.'}],
  ['determine', {meaning:'决定',pos:'n.'}],
  ['develop', {meaning:'发展',pos:'n.'}],
  ['device', {meaning:'装置',pos:'n.'}],
  ['diary', {meaning:'日记\n日记簿',pos:'n.'}],
  ['die', {meaning:'死亡',pos:'n.'}],
  ['diet', {meaning:'日常饮食',pos:'n.'}],
  ['different', {meaning:'不同的\n差动',pos:'n.'}],
  ['difficult', {meaning:'困难的',pos:'n.'}],
  ['dig', {meaning:'挖',pos:'n.'}],
  ['dim', {meaning:'暗淡的',pos:'n.'}],
  ['din', {meaning:'喧嚣\nv. 絮絮不休地说',pos:'n.'}],
  ['dinner', {meaning:'晚餐',pos:'n.'}],
  ['dip', {meaning:'浸',pos:'n.'}],
  ['direct', {meaning:'直接的',pos:'n.'}],
  ['director', {meaning:'主管',pos:'n.'}],
  ['dirt', {meaning:'污垢',pos:'n.'}],
  ['dirty', {meaning:'肮脏的',pos:'n.'}],
  ['disc', {meaning:'圆盘',pos:'n.'}],
  ['discuss', {meaning:'讨论',pos:'n.'}],
  ['disease', {meaning:'疾病',pos:'n.'}],
  ['dish', {meaning:'盘子',pos:'n.'}],
  ['disk', {meaning:'圆盘',pos:'n.'}],
  ['divide', {meaning:'分开',pos:'n.'}],
  ['dna', {meaning:'脱氧核糖核酸\n无效数据',pos:'n.'}],
  ['doctor', {meaning:'医生',pos:'n.'}],
  ['dog', {meaning:'狗',pos:'n.'}],
  ['don', {meaning:'西班牙贵族(或绅士)',pos:'n.'}],
  ['door', {meaning:'门',pos:'n.'}],
  ['dot', {meaning:'点',pos:'n.'}],
  ['double', {meaning:'两倍\na. 两倍的',pos:'n.'}],
  ['doubt', {meaning:'怀疑',pos:'n.'}],
  ['down', {meaning:'向下的\nadv. 下',pos:'n.'}],
  ['dozen', {meaning:'打',pos:'n.'}],
  ['draft', {meaning:'气流',pos:'n.'}],
  ['drag', {meaning:'拖',pos:'n.'}],
  ['drama', {meaning:'戏剧',pos:'n.'}],
  ['draw', {meaning:'拉',pos:'n.'}],
  ['dream', {meaning:'梦',pos:'n.'}],
  ['dress', {meaning:'服装',pos:'n.'}],
  ['drink', {meaning:'饮料',pos:'n.'}],
  ['drive', {meaning:'驾车',pos:'n.'}],
  ['drop', {meaning:'滴',pos:'n.'}],
  ['drug', {meaning:'药',pos:'n.'}],
  ['drum', {meaning:'鼓',pos:'n.'}],
  ['drunk', {meaning:'喝醉了的\ndrink的过去式',pos:'n.'}],
  ['dry', {meaning:'干的',pos:'n.'}],
  ['dub', {meaning:'配音',pos:'n.'}],
  ['due', {meaning:'应得的东西',pos:'n.'}],
  ['dull', {meaning:'钝的',pos:'n.'}],
  ['dump', {meaning:'垃圾场\nvt. 倾倒',pos:'n.'}],
  ['duo', {meaning:'二重唱',pos:'n.'}],
  ['during', {meaning:'在...的时候',pos:'n.'}],
  ['dust', {meaning:'灰尘',pos:'n.'}],
  ['duty', {meaning:'责任',pos:'n.'}],
  ['dvd', {meaning:'数字化视频光盘（Digital Video Disk）',pos:'n.'}],
  ['dye', {meaning:'颜料',pos:'n.'}],
  ['dying', {meaning:'垂死的\n快要死的',pos:'n.'}],
  ['each', {meaning:'每个',pos:'n.'}],
  ['ear', {meaning:'耳朵',pos:'n.'}],
  ['early', {meaning:'早的',pos:'n.'}],
  ['earn', {meaning:'赚得',pos:'n.'}],
  ['earth', {meaning:'地球',pos:'n.'}],
  ['ease', {meaning:'安乐',pos:'n.'}],
  ['easily', {meaning:'容易地',pos:'n.'}],
  ['east', {meaning:'东方',pos:'n.'}],
  ['easy', {meaning:'容易的',pos:'n.'}],
  ['eat', {meaning:'吃',pos:'n.'}],
  ['echo', {meaning:'回声',pos:'n.'}],
  ['economic', {meaning:'经济上的',pos:'n.'}],
  ['economy', {meaning:'经济',pos:'n.'}],
  ['edge', {meaning:'边缘',pos:'n.'}],
  ['edit', {meaning:'编辑',pos:'n.'}],
  ['editor', {meaning:'编者',pos:'n.'}],
  ['education', {meaning:'教育',pos:'n.'}],
  ['eel', {meaning:'鳗鱼',pos:'n.'}],
  ['effect', {meaning:'结果',pos:'n.'}],
  ['effort', {meaning:'努力',pos:'n.'}],
  ['egg', {meaning:'蛋',pos:'n.'}],
  ['ego', {meaning:'自我\n自我',pos:'n.'}],
  ['either', {meaning:'(两者之中)任一的',pos:'n.'}],
  ['elbow', {meaning:'手肘',pos:'n.'}],
  ['elect', {meaning:'当选人',pos:'n.'}],
  ['election', {meaning:'选举',pos:'n.'}],
  ['elk', {meaning:'麋鹿',pos:'n.'}],
  ['elm', {meaning:'榆树\nunix操作系统的信件处理程序',pos:'n.'}],
  ['else', {meaning:'别的',pos:'n.'}],
  ['emerge', {meaning:'浮现',pos:'n.'}],
  ['empty', {meaning:'空的',pos:'n.'}],
  ['end', {meaning:'结束',pos:'n.'}],
  ['enemy', {meaning:'敌人',pos:'n.'}],
  ['energy', {meaning:'精力',pos:'n.'}],
  ['engage', {meaning:'答应',pos:'n.'}],
  ['engine', {meaning:'引擎',pos:'n.'}],
  ['enjoy', {meaning:'享受',pos:'n.'}],
  ['enough', {meaning:'充足',pos:'n.'}],
  ['ensure', {meaning:'确定',pos:'n.'}],
  ['enter', {meaning:'进入',pos:'n.'}],
  ['entire', {meaning:'整个',pos:'n.'}],
  ['entry', {meaning:'登录',pos:'n.'}],
  ['equal', {meaning:'对手',pos:'n.'}],
  ['era', {meaning:'时代',pos:'n.'}],
  ['err', {meaning:'犯错',pos:'n.'}],
  ['error', {meaning:'错误',pos:'n.'}],
  ['escape', {meaning:'逃亡',pos:'n.'}],
  ['essay', {meaning:'随笔',pos:'n.'}],
  ['establish', {meaning:'建立',pos:'n.'}],
  ['etc', {meaning:'及其他',pos:'n.'}],
  ['euro', {meaning:'欧元（欧盟的统一货币单位）',pos:'n.'}],
  ['eve', {meaning:'前夕',pos:'n.'}],
  ['even', {meaning:'平坦的',pos:'n.'}],
  ['event', {meaning:'事件',pos:'n.'}],
  ['ever', {meaning:'曾经',pos:'n.'}],
  ['every', {meaning:'每一',pos:'n.'}],
  ['everyone', {meaning:'每个人',pos:'n.'}],
  ['evidence', {meaning:'根据',pos:'n.'}],
  ['evil', {meaning:'邪恶',pos:'n.'}],
  ['exact', {meaning:'精确的',pos:'n.'}],
  ['exam', {meaning:'考试',pos:'n.'}],
  ['example', {meaning:'例子',pos:'n.'}],
  ['except', {meaning:'除',pos:'n.'}],
  ['executive', {meaning:'执行部门',pos:'n.'}],
  ['exist', {meaning:'存在',pos:'n.'}],
  ['exit', {meaning:'出口',pos:'n.'}],
  ['expand', {meaning:'使膨胀',pos:'n.'}],
  ['expect', {meaning:'预期',pos:'n.'}],
  ['expert', {meaning:'专家',pos:'n.'}],
  ['explain', {meaning:'解释',pos:'n.'}],
  ['export', {meaning:'输出品',pos:'n.'}],
  ['extend', {meaning:'扩充',pos:'n.'}],
  ['extra', {meaning:'额外的事物',pos:'n.'}],
  ['eye', {meaning:'眼睛',pos:'n.'}],
  ['face', {meaning:'脸',pos:'n.'}],
  ['fact', {meaning:'事实',pos:'n.'}],
  ['factor', {meaning:'因素',pos:'n.'}],
  ['fad', {meaning:'时尚\n黄素腺嘌呤二核苷酸',pos:'n.'}],
  ['fade', {meaning:'褪色',pos:'n.'}],
  ['fail', {meaning:'失败',pos:'n.'}],
  ['faint', {meaning:'昏厥',pos:'n.'}],
  ['fair', {meaning:'展览会',pos:'n.'}],
  ['faith', {meaning:'信心',pos:'n.'}],
  ['fall', {meaning:'落下',pos:'n.'}],
  ['false', {meaning:'错误的',pos:'n.'}],
  ['fame', {meaning:'名望',pos:'n.'}],
  ['family', {meaning:'家庭',pos:'n.'}],
  ['famous', {meaning:'出名的',pos:'n.'}],
  ['fan', {meaning:'风扇',pos:'n.'}],
  ['far', {meaning:'远的',pos:'n.'}],
  ['fare', {meaning:'费用',pos:'n.'}],
  ['farm', {meaning:'农场',pos:'n.'}],
  ['farmer', {meaning:'农夫',pos:'n.'}],
  ['fast', {meaning:'快速的',pos:'n.'}],
  ['fat', {meaning:'脂肪',pos:'n.'}],
  ['fate', {meaning:'命运',pos:'n.'}],
  ['father', {meaning:'父亲',pos:'n.'}],
  ['fault', {meaning:'过错',pos:'n.'}],
  ['fax', {meaning:'传真\nvt. 发传真\n传真系统',pos:'n.'}],
  ['fear', {meaning:'恐怖',pos:'n.'}],
  ['federal', {meaning:'联邦的',pos:'n.'}],
  ['fee', {meaning:'费用',pos:'n.'}],
  ['feed', {meaning:'饲料',pos:'n.'}],
  ['feel', {meaning:'感觉',pos:'n.'}],
  ['feeling', {meaning:'摸',pos:'n.'}],
  ['fellow', {meaning:'男人',pos:'n.'}],
  ['female', {meaning:'女性',pos:'n.'}],
  ['fence', {meaning:'围墙',pos:'n.'}],
  ['fever', {meaning:'发烧',pos:'n.'}],
  ['few', {meaning:'很少的',pos:'n.'}],
  ['field', {meaning:'领域',pos:'n.'}],
  ['fig', {meaning:'无花果',pos:'n.'}],
  ['fight', {meaning:'打架',pos:'n.'}],
  ['figure', {meaning:'数字',pos:'n.'}],
  ['file', {meaning:'档案',pos:'n.'}],
  ['fill', {meaning:'装满',pos:'n.'}],
  ['film', {meaning:'软片',pos:'n.'}],
  ['fin', {meaning:'鳍',pos:'n.'}],
  ['final', {meaning:'期末考试',pos:'n.'}],
  ['finally', {meaning:'最后',pos:'n.'}],
  ['financial', {meaning:'财政的',pos:'n.'}],
  ['find', {meaning:'发现',pos:'n.'}],
  ['fine', {meaning:'罚款',pos:'n.'}],
  ['finger', {meaning:'手指',pos:'n.'}],
  ['finish', {meaning:'完成',pos:'n.'}],
  ['fir', {meaning:'枞树',pos:'n.'}],
  ['fire', {meaning:'火',pos:'n.'}],
  ['firm', {meaning:'公司',pos:'n.'}],
  ['first', {meaning:'首先',pos:'n.'}],
  ['fish', {meaning:'鱼',pos:'n.'}],
  ['fit', {meaning:'适宜',pos:'n.'}],
  ['five', {meaning:'五',pos:'n.'}],
  ['fix', {meaning:'使固定',pos:'n.'}],
  ['fixed', {meaning:'固定的',pos:'n.'}],
  ['flag', {meaning:'标志',pos:'n.'}],
  ['flame', {meaning:'火焰',pos:'n.'}],
  ['flash', {meaning:'闪光',pos:'n.'}],
  ['flat', {meaning:'平坦的',pos:'n.'}],
  ['flee', {meaning:'逃避',pos:'n.'}],
  ['flesh', {meaning:'肉',pos:'n.'}],
  ['flight', {meaning:'飞行',pos:'n.'}],
  ['float', {meaning:'漂流物',pos:'n.'}],
  ['flood', {meaning:'洪水',pos:'n.'}],
  ['floor', {meaning:'地板',pos:'n.'}],
  ['flour', {meaning:'面粉',pos:'n.'}],
  ['flow', {meaning:'流程',pos:'n.'}],
  ['flower', {meaning:'花',pos:'n.'}],
  ['flu', {meaning:'流感',pos:'n.'}],
  ['fly', {meaning:'苍蝇',pos:'n.'}],
  ['focus', {meaning:'焦点',pos:'n.'}],
  ['foe', {meaning:'仇敌',pos:'n.'}],
  ['fog', {meaning:'雾',pos:'n.'}],
  ['fold', {meaning:'折层',pos:'n.'}],
  ['folk', {meaning:'人们',pos:'n.'}],
  ['follow', {meaning:'跟随',pos:'n.'}],
  ['food', {meaning:'食物',pos:'n.'}],
  ['fool', {meaning:'愚人',pos:'n.'}],
  ['foot', {meaning:'脚',pos:'n.'}],
  ['for', {meaning:'为',pos:'n.'}],
  ['force', {meaning:'力量',pos:'n.'}],
  ['forest', {meaning:'森林',pos:'n.'}],
  ['forget', {meaning:'忘记',pos:'n.'}],
  ['fork', {meaning:'叉子',pos:'n.'}],
  ['form', {meaning:'形状',pos:'n.'}],
  ['formal', {meaning:'正式的',pos:'n.'}],
  ['former', {meaning:'从前的',pos:'n.'}],
  ['forward', {meaning:'向前的',pos:'n.'}],
  ['found', {meaning:'建立',pos:'n.'}],
  ['four', {meaning:'四',pos:'n.'}],
  ['fox', {meaning:'狐狸',pos:'n.'}],
  ['frame', {meaning:'框',pos:'n.'}],
  ['free', {meaning:'自由的',pos:'n.'}],
  ['fresh', {meaning:'新鲜的',pos:'n.'}],
  ['friend', {meaning:'朋友',pos:'n.'}],
  ['from', {meaning:'从',pos:'n.'}],
  ['front', {meaning:'前面',pos:'n.'}],
  ['fruit', {meaning:'水果',pos:'n.'}],
  ['fry', {meaning:'油炸食物',pos:'n.'}],
  ['fuel', {meaning:'燃料',pos:'n.'}],
  ['full', {meaning:'全部',pos:'n.'}],
  ['fully', {meaning:'十分地',pos:'n.'}],
  ['fun', {meaning:'乐趣',pos:'n.'}],
  ['fund', {meaning:'基金',pos:'n.'}],
  ['funny', {meaning:'好笑的',pos:'n.'}],
  ['fur', {meaning:'毛皮\nvt. 以毛皮制作',pos:'n.'}],
  ['future', {meaning:'未来',pos:'n.'}],
  ['gag', {meaning:'箝口物',pos:'n.'}],
  ['gain', {meaning:'增益',pos:'n.'}],
  ['gal', {meaning:'伽(重力加速度单位',pos:'n.'}],
  ['game', {meaning:'比赛',pos:'n.'}],
  ['gang', {meaning:'队',pos:'n.'}],
  ['gap', {meaning:'缝隙',pos:'n.'}],
  ['garden', {meaning:'花园',pos:'n.'}],
  ['gas', {meaning:'气体',pos:'n.'}],
  ['gate', {meaning:'门',pos:'n.'}],
  ['gather', {meaning:'集合',pos:'n.'}],
  ['gay', {meaning:'欢快的',pos:'n.'}],
  ['gdp', {meaning:'鸟苷二磷酸',pos:'n.'}],
  ['gear', {meaning:'齿轮',pos:'n.'}],
  ['gee', {meaning:'马',pos:'n.'}],
  ['gel', {meaning:'胶化体',pos:'n.'}],
  ['gem', {meaning:'珠宝',pos:'n.'}],
  ['gene', {meaning:'基因\n基因(遗传因子)',pos:'n.'}],
  ['general', {meaning:'一般',pos:'n.'}],
  ['get', {meaning:'得到',pos:'n.'}],
  ['giant', {meaning:'巨人',pos:'n.'}],
  ['gift', {meaning:'礼物',pos:'n.'}],
  ['gig', {meaning:'旋转物',pos:'n.'}],
  ['gin', {meaning:'杜松子酒',pos:'n.'}],
  ['girl', {meaning:'女孩',pos:'n.'}],
  ['give', {meaning:'弹性',pos:'n.'}],
  ['glad', {meaning:'高兴的',pos:'n.'}],
  ['glass', {meaning:'玻璃',pos:'n.'}],
  ['global', {meaning:'通用的',pos:'n.'}],
  ['glove', {meaning:'手套\nvt. 给...戴手套',pos:'n.'}],
  ['glue', {meaning:'胶',pos:'n.'}],
  ['gnp', {meaning:'国民生产总值\n国民生产毛额',pos:'n.'}],
  ['goal', {meaning:'目标',pos:'n.'}],
  ['god', {meaning:'上帝',pos:'n.'}],
  ['gold', {meaning:'黄金',pos:'n.'}],
  ['golf', {meaning:'高尔夫球\nvi. 打高尔夫球',pos:'n.'}],
  ['good', {meaning:'善行',pos:'n.'}],
  ['gop', {meaning:'大老党（美国共和党的别称）（Grand Old Party）；地面观测站（Ground Observation Post）',pos:'n.'}],
  ['grab', {meaning:'抓握',pos:'n.'}],
  ['grade', {meaning:'等级',pos:'n.'}],
  ['grain', {meaning:'谷粒',pos:'n.'}],
  ['gram', {meaning:'克',pos:'n.'}],
  ['grand', {meaning:'庄重的',pos:'n.'}],
  ['grant', {meaning:'授予',pos:'n.'}],
  ['grass', {meaning:'草',pos:'n.'}],
  ['grave', {meaning:'墓穴',pos:'n.'}],
  ['gray', {meaning:'灰色',pos:'n.'}],
  ['great', {meaning:'大的',pos:'n.'}],
  ['green', {meaning:'绿色',pos:'n.'}],
  ['grey', {meaning:'灰色\na. 灰色的',pos:'n.'}],
  ['grip', {meaning:'紧握',pos:'n.'}],
  ['ground', {meaning:'土地',pos:'n.'}],
  ['group', {meaning:'团体',pos:'n.'}],
  ['grow', {meaning:'种植',pos:'n.'}],
  ['growth', {meaning:'生长',pos:'n.'}],
  ['guard', {meaning:'守卫者',pos:'n.'}],
  ['guess', {meaning:'猜测',pos:'n.'}],
  ['guest', {meaning:'客人',pos:'n.'}],
  ['guide', {meaning:'引导者',pos:'n.'}],
  ['gum', {meaning:'树胶',pos:'n.'}],
  ['gun', {meaning:'枪\n枪',pos:'n.'}],
  ['gut', {meaning:'剧情',pos:'n.'}],
  ['guy', {meaning:'家伙',pos:'n.'}],
  ['gym', {meaning:'+体育馆',pos:'n.'}],
  ['habit', {meaning:'习惯',pos:'n.'}],
  ['hair', {meaning:'头发',pos:'n.'}],
  ['half', {meaning:'一半',pos:'n.'}],
  ['hall', {meaning:'门厅',pos:'n.'}],
  ['ham', {meaning:'火腿',pos:'n.'}],
  ['hand', {meaning:'手',pos:'n.'}],
  ['handle', {meaning:'柄',pos:'n.'}],
  ['hang', {meaning:'悬挂',pos:'n.'}],
  ['happen', {meaning:'发生',pos:'n.'}],
  ['happy', {meaning:'快乐的',pos:'n.'}],
  ['hard', {meaning:'坚硬的',pos:'n.'}],
  ['hardly', {meaning:'刚刚',pos:'n.'}],
  ['harm', {meaning:'伤害',pos:'n.'}],
  ['hat', {meaning:'帽子\nvt. 给...戴帽子',pos:'n.'}],
  ['hate', {meaning:'憎恨',pos:'n.'}],
  ['have', {meaning:'有',pos:'n.'}],
  ['hay', {meaning:'干草\nvt. 制干草',pos:'n.'}],
  ['head', {meaning:'头',pos:'n.'}],
  ['heal', {meaning:'痊愈\nvt. 使复原',pos:'n.'}],
  ['health', {meaning:'健康',pos:'n.'}],
  ['hear', {meaning:'听到',pos:'n.'}],
  ['heart', {meaning:'心',pos:'n.'}],
  ['heat', {meaning:'热',pos:'n.'}],
  ['heavy', {meaning:'重的',pos:'n.'}],
  ['heel', {meaning:'脚后跟',pos:'n.'}],
  ['hell', {meaning:'地狱',pos:'n.'}],
  ['hello', {meaning:'喂',pos:'n.'}],
  ['help', {meaning:'帮忙',pos:'n.'}],
  ['hem', {meaning:'边缘',pos:'n.'}],
  ['hen', {meaning:'母鸡',pos:'n.'}],
  ['hence', {meaning:'因此',pos:'n.'}],
  ['her', {meaning:'她的',pos:'n.'}],
  ['here', {meaning:'在这里',pos:'n.'}],
  ['hero', {meaning:'英雄',pos:'n.'}],
  ['hers', {meaning:'她的',pos:'n.'}],
  ['herself', {meaning:'她自己',pos:'n.'}],
  ['hey', {meaning:'嗨',pos:'n.'}],
  ['hide', {meaning:'兽皮',pos:'n.'}],
  ['high', {meaning:'高度',pos:'n.'}],
  ['highly', {meaning:'非常',pos:'n.'}],
  ['hill', {meaning:'小山',pos:'n.'}],
  ['him', {meaning:'他',pos:'n.'}],
  ['himself', {meaning:'他自己',pos:'n.'}],
  ['hint', {meaning:'暗示',pos:'n.'}],
  ['hip', {meaning:'臀部',pos:'n.'}],
  ['hire', {meaning:'租金',pos:'n.'}],
  ['his', {meaning:'他的\n组氨酸',pos:'n.'}],
  ['history', {meaning:'历史',pos:'n.'}],
  ['hit', {meaning:'打击',pos:'n.'}],
  ['hmm', {meaning:'隐马尔可夫模型（Hidden Markov Model）；Hardware Maintenance Manual；Hyundai Merchant Marine',pos:'n.'}],
  ['hmo', {meaning:'休克尔分子轨道法',pos:'n.'}],
  ['hog', {meaning:'猪',pos:'n.'}],
  ['hold', {meaning:'把握',pos:'n.'}],
  ['hole', {meaning:'孔',pos:'n.'}],
  ['holy', {meaning:'神圣的',pos:'n.'}],
  ['home', {meaning:'家',pos:'n.'}],
  ['hook', {meaning:'钩',pos:'n.'}],
  ['hop', {meaning:'单脚跳',pos:'n.'}],
  ['hope', {meaning:'希望',pos:'n.'}],
  ['horn', {meaning:'角',pos:'n.'}],
  ['horse', {meaning:'马',pos:'n.'}],
  ['hospital', {meaning:'医院\n医院',pos:'n.'}],
  ['host', {meaning:'主人',pos:'n.'}],
  ['hot', {meaning:'热的',pos:'n.'}],
  ['hotel', {meaning:'旅馆',pos:'n.'}],
  ['hour', {meaning:'小时',pos:'n.'}],
  ['house', {meaning:'房子',pos:'n.'}],
  ['how', {meaning:'如何',pos:'n.'}],
  ['however', {meaning:'然而',pos:'n.'}],
  ['hub', {meaning:'毂',pos:'n.'}],
  ['hue', {meaning:'样子',pos:'n.'}],
  ['hug', {meaning:'紧抱',pos:'n.'}],
  ['huge', {meaning:'极大的',pos:'n.'}],
  ['huh', {meaning:'哼',pos:'n.'}],
  ['hum', {meaning:'嗡嗡声',pos:'n.'}],
  ['human', {meaning:'人',pos:'n.'}],
  ['hunt', {meaning:'狩猎',pos:'n.'}],
  ['hurry', {meaning:'匆忙',pos:'n.'}],
  ['hurt', {meaning:'伤害',pos:'n.'}],
  ['husband', {meaning:'丈夫',pos:'n.'}],
  ['hut', {meaning:'小屋',pos:'n.'}],
  ['ice', {meaning:'冰',pos:'n.'}],
  ['icy', {meaning:'冰的',pos:'n.'}],
  ['idea', {meaning:'主意',pos:'n.'}],
  ['ideal', {meaning:'理想',pos:'n.'}],
  ['identify', {meaning:'识别',pos:'n.'}],
  ['ignore', {meaning:'不理睬',pos:'n.'}],
  ['ill', {meaning:'疾病',pos:'n.'}],
  ['image', {meaning:'影像',pos:'n.'}],
  ['imagine', {meaning:'想像',pos:'n.'}],
  ['impact', {meaning:'冲击',pos:'n.'}],
  ['imply', {meaning:'暗示',pos:'n.'}],
  ['import', {meaning:'进口货',pos:'n.'}],
  ['important', {meaning:'重要的',pos:'n.'}],
  ['impose', {meaning:'征(税)',pos:'n.'}],
  ['inch', {meaning:'英寸',pos:'n.'}],
  ['include', {meaning:'包括',pos:'n.'}],
  ['including', {meaning:'包含',pos:'n.'}],
  ['income', {meaning:'收入',pos:'n.'}],
  ['increase', {meaning:'增加',pos:'n.'}],
  ['indeed', {meaning:'的确',pos:'n.'}],
  ['index', {meaning:'索引',pos:'n.'}],
  ['indicate', {meaning:'显示',pos:'n.'}],
  ['industry', {meaning:'勤劳',pos:'n.'}],
  ['injury', {meaning:'伤害',pos:'n.'}],
  ['ink', {meaning:'墨水',pos:'n.'}],
  ['inn', {meaning:'旅馆',pos:'n.'}],
  ['inner', {meaning:'内部的',pos:'n.'}],
  ['inside', {meaning:'内部',pos:'n.'}],
  ['insist', {meaning:'坚持',pos:'n.'}],
  ['intend', {meaning:'计划',pos:'n.'}],
  ['interest', {meaning:'兴趣',pos:'n.'}],
  ['into', {meaning:'进入...之内',pos:'n.'}],
  ['invite', {meaning:'邀请',pos:'n.'}],
  ['involve', {meaning:'包括',pos:'n.'}],
  ['ion', {meaning:'离子\n离子',pos:'n.'}],
  ['iron', {meaning:'铁',pos:'n.'}],
  ['island', {meaning:'岛',pos:'n.'}],
  ['issue', {meaning:'发行',pos:'n.'}],
  ['item', {meaning:'项目',pos:'n.'}],
  ['its', {meaning:'它的',pos:'n.'}],
  ['itself', {meaning:'它本身',pos:'n.'}],
  ['ivy', {meaning:'常春藤\na. 学院的',pos:'n.'}],
  ['jab', {meaning:'刺',pos:'n.'}],
  ['jail', {meaning:'监牢',pos:'n.'}],
  ['jam', {meaning:'果酱',pos:'n.'}],
  ['jar', {meaning:'广口瓶',pos:'n.'}],
  ['jaw', {meaning:'颚',pos:'n.'}],
  ['jazz', {meaning:'爵士乐',pos:'n.'}],
  ['jeans', {meaning:'工装裤',pos:'n.'}],
  ['jet', {meaning:'喷射流',pos:'n.'}],
  ['jew', {meaning:'犹太人',pos:'n.'}],
  ['jig', {meaning:'吉格快步舞',pos:'n.'}],
  ['job', {meaning:'工作',pos:'n.'}],
  ['jog', {meaning:'轻推',pos:'n.'}],
  ['join', {meaning:'参加',pos:'n.'}],
  ['joint', {meaning:'连接处',pos:'n.'}],
  ['joke', {meaning:'笑话',pos:'n.'}],
  ['jot', {meaning:'少量',pos:'n.'}],
  ['joy', {meaning:'欢喜',pos:'n.'}],
  ['judge', {meaning:'法官',pos:'n.'}],
  ['jug', {meaning:'水壶',pos:'n.'}],
  ['juice', {meaning:'汁',pos:'n.'}],
  ['july', {meaning:'七月',pos:'n.'}],
  ['jump', {meaning:'跳跃',pos:'n.'}],
  ['june', {meaning:'六月',pos:'n.'}],
  ['jury', {meaning:'陪审团',pos:'n.'}],
  ['just', {meaning:'正直的',pos:'n.'}],
  ['jut', {meaning:'尖端',pos:'n.'}],
  ['keen', {meaning:'锋利的',pos:'n.'}],
  ['keep', {meaning:'生计',pos:'n.'}],
  ['key', {meaning:'钥匙',pos:'n.'}],
  ['kick', {meaning:'踢',pos:'n.'}],
  ['kid', {meaning:'小山羊',pos:'n.'}],
  ['kill', {meaning:'杀',pos:'n.'}],
  ['kin', {meaning:'亲戚',pos:'n.'}],
  ['kind', {meaning:'种类',pos:'n.'}],
  ['king', {meaning:'国王',pos:'n.'}],
  ['kiss', {meaning:'吻\nvt. 吻\nvi. 接吻',pos:'n.'}],
  ['kit', {meaning:'装备',pos:'n.'}],
  ['knee', {meaning:'膝',pos:'n.'}],
  ['knife', {meaning:'小刀',pos:'n.'}],
  ['knit', {meaning:'编织',pos:'n.'}],
  ['knock', {meaning:'敲',pos:'n.'}],
  ['knot', {meaning:'结',pos:'n.'}],
  ['know', {meaning:'知道',pos:'n.'}],
  ['knowledge', {meaning:'知识',pos:'n.'}],
  ['lab', {meaning:'实验室',pos:'n.'}],
  ['label', {meaning:'标签',pos:'n.'}],
  ['lack', {meaning:'缺乏',pos:'n.'}],
  ['lad', {meaning:'青年',pos:'n.'}],
  ['lady', {meaning:'淑女',pos:'n.'}],
  ['lag', {meaning:'落后',pos:'n.'}],
  ['lake', {meaning:'湖',pos:'n.'}],
  ['lamp', {meaning:'灯\nvt. 照亮\n逻辑模拟分析系统',pos:'n.'}],
  ['land', {meaning:'陆地',pos:'n.'}],
  ['lane', {meaning:'小路',pos:'n.'}],
  ['language', {meaning:'语言',pos:'n.'}],
  ['lap', {meaning:'膝盖',pos:'n.'}],
  ['large', {meaning:'大的',pos:'n.'}],
  ['last', {meaning:'最后的',pos:'n.'}],
  ['late', {meaning:'迟的',pos:'n.'}],
  ['later', {meaning:'以后',pos:'n.'}],
  ['laugh', {meaning:'笑',pos:'n.'}],
  ['launch', {meaning:'下水',pos:'n.'}],
  ['law', {meaning:'法律',pos:'n.'}],
  ['lawyer', {meaning:'律师\n律师',pos:'n.'}],
  ['lax', {meaning:'松的',pos:'n.'}],
  ['lay', {meaning:'放置',pos:'n.'}],
  ['layer', {meaning:'层',pos:'n.'}],
  ['lazy', {meaning:'懒惰的',pos:'n.'}],
  ['lcd', {meaning:'液晶显示器\n液晶显示器',pos:'n.'}],
  ['lead', {meaning:'铅',pos:'n.'}],
  ['leader', {meaning:'领导者',pos:'n.'}],
  ['leaf', {meaning:'叶',pos:'n.'}],
  ['league', {meaning:'同盟',pos:'n.'}],
  ['leak', {meaning:'漏洞',pos:'n.'}],
  ['lean', {meaning:'瘦肉',pos:'n.'}],
  ['leap', {meaning:'跳跃',pos:'n.'}],
  ['learn', {meaning:'学习；认识到；得知',pos:'n.'}],
  ['least', {meaning:'最少',pos:'n.'}],
  ['leave', {meaning:'许可',pos:'n.'}],
  ['left', {meaning:'左边的',pos:'n.'}],
  ['leg', {meaning:'腿',pos:'n.'}],
  ['legal', {meaning:'法律的',pos:'n.'}],
  ['lemon', {meaning:'柠檬',pos:'n.'}],
  ['lend', {meaning:'借',pos:'n.'}],
  ['length', {meaning:'长度',pos:'n.'}],
  ['lens', {meaning:'透镜',pos:'n.'}],
  ['less', {meaning:'较少',pos:'n.'}],
  ['lesson', {meaning:'课',pos:'n.'}],
  ['let', {meaning:'让',pos:'n.'}],
  ['letter', {meaning:'信',pos:'n.'}],
  ['level', {meaning:'水平',pos:'n.'}],
  ['lid', {meaning:'盖子',pos:'n.'}],
  ['lie', {meaning:'谎言',pos:'n.'}],
  ['life', {meaning:'生活',pos:'n.'}],
  ['lift', {meaning:'举起',pos:'n.'}],
  ['light', {meaning:'光',pos:'n.'}],
  ['like', {meaning:'相似的',pos:'n.'}],
  ['likely', {meaning:'有可能的',pos:'n.'}],
  ['limit', {meaning:'界限',pos:'n.'}],
  ['line', {meaning:'列',pos:'n.'}],
  ['link', {meaning:'环',pos:'n.'}],
  ['lip', {meaning:'唇',pos:'n.'}],
  ['list', {meaning:'目录',pos:'n.'}],
  ['listen', {meaning:'听',pos:'n.'}],
  ['little', {meaning:'一点点',pos:'n.'}],
  ['live', {meaning:'活的',pos:'n.'}],
  ['living', {meaning:'生活',pos:'n.'}],
  ['load', {meaning:'负荷',pos:'n.'}],
  ['loan', {meaning:'贷款',pos:'n.'}],
  ['local', {meaning:'地方性的',pos:'n.'}],
  ['lock', {meaning:'锁',pos:'n.'}],
  ['log', {meaning:'记录',pos:'n.'}],
  ['logic', {meaning:'逻辑',pos:'n.'}],
  ['long', {meaning:'长的',pos:'n.'}],
  ['look', {meaning:'一看',pos:'n.'}],
  ['loose', {meaning:'发射',pos:'n.'}],
  ['lord', {meaning:'统治者',pos:'n.'}],
  ['lose', {meaning:'遗失',pos:'n.'}],
  ['loss', {meaning:'损失',pos:'n.'}],
  ['lost', {meaning:'失去的',pos:'n.'}],
  ['lot', {meaning:'运气',pos:'n.'}],
  ['loud', {meaning:'大声的',pos:'n.'}],
  ['love', {meaning:'爱',pos:'n.'}],
  ['lover', {meaning:'爱人',pos:'n.'}],
  ['low', {meaning:'低点',pos:'n.'}],
  ['lsd', {meaning:'迷幻剂烈性麻醉药\n最小有效位',pos:'n.'}],
  ['luck', {meaning:'运气',pos:'n.'}],
  ['lucky', {meaning:'幸运的',pos:'n.'}],
  ['lug', {meaning:'拖',pos:'n.'}],
  ['lump', {meaning:'块',pos:'n.'}],
  ['lunch', {meaning:'午餐',pos:'n.'}],
  ['lung', {meaning:'肺',pos:'n.'}],
  ['mad', {meaning:'疯狂的',pos:'n.'}],
  ['magic', {meaning:'魔术',pos:'n.'}],
  ['mail', {meaning:'邮件',pos:'n.'}],
  ['main', {meaning:'主要部分',pos:'n.'}],
  ['mainly', {meaning:'主要地',pos:'n.'}],
  ['maintain', {meaning:'维持',pos:'n.'}],
  ['major', {meaning:'主修课',pos:'n.'}],
  ['make', {meaning:'制造',pos:'n.'}],
  ['male', {meaning:'男人',pos:'n.'}],
  ['mall', {meaning:'林荫路',pos:'n.'}],
  ['man', {meaning:'男人',pos:'n.'}],
  ['manage', {meaning:'处理\nvt. 管理',pos:'n.'}],
  ['manager', {meaning:'经理',pos:'n.'}],
  ['many', {meaning:'多数',pos:'n.'}],
  ['map', {meaning:'地图',pos:'n.'}],
  ['mar', {meaning:'损毁',pos:'n.'}],
  ['march', {meaning:'三月',pos:'n.'}],
  ['mark', {meaning:'标志',pos:'n.'}],
  ['market', {meaning:'市场',pos:'n.'}],
  ['marry', {meaning:'与...结婚',pos:'n.'}],
  ['mask', {meaning:'面具',pos:'n.'}],
  ['mass', {meaning:'块',pos:'n.'}],
  ['master', {meaning:'主人',pos:'n.'}],
  ['mat', {meaning:'垫',pos:'n.'}],
  ['match', {meaning:'比赛',pos:'n.'}],
  ['mate', {meaning:'配偶',pos:'n.'}],
  ['material', {meaning:'材料',pos:'n.'}],
  ['matter', {meaning:'事件',pos:'n.'}],
  ['may', {meaning:'五月\naux. 愿能',pos:'n.'}],
  ['maybe', {meaning:'也许',pos:'n.'}],
  ['mayor', {meaning:'市长\n市长',pos:'n.'}],
  ['mba', {meaning:'工商管理学硕士（Master of Business Administration）；海洋生物协会（Marine Biological Association）；主要战区（Main Battle Area）',pos:'n.'}],
  ['meal', {meaning:'一餐',pos:'n.'}],
  ['mean', {meaning:'低劣的',pos:'n.'}],
  ['meat', {meaning:'肉',pos:'n.'}],
  ['media', {meaning:'媒体\n媒质',pos:'n.'}],
  ['medical', {meaning:'医生',pos:'n.'}],
  ['meet', {meaning:'会',pos:'n.'}],
  ['meeting', {meaning:'会议',pos:'n.'}],
  ['melt', {meaning:'熔化',pos:'n.'}],
  ['member', {meaning:'成员',pos:'n.'}],
  ['memory', {meaning:'记忆',pos:'n.'}],
  ['menu', {meaning:'菜单',pos:'n.'}],
  ['mere', {meaning:'小湖',pos:'n.'}],
  ['mess', {meaning:'食堂',pos:'n.'}],
  ['message', {meaning:'消息',pos:'n.'}],
  ['metal', {meaning:'金属',pos:'n.'}],
  ['method', {meaning:'方法',pos:'n.'}],
  ['mid', {meaning:'中间的',pos:'n.'}],
  ['middle', {meaning:'中央',pos:'n.'}],
  ['mild', {meaning:'温和的',pos:'n.'}],
  ['mile', {meaning:'英里',pos:'n.'}],
  ['military', {meaning:'军队\na. 军事的',pos:'n.'}],
  ['milk', {meaning:'奶',pos:'n.'}],
  ['mill', {meaning:'压榨机',pos:'n.'}],
  ['mind', {meaning:'思想',pos:'n.'}],
  ['mine', {meaning:'矿',pos:'n.'}],
  ['minister', {meaning:'部长',pos:'n.'}],
  ['minor', {meaning:'未成年人',pos:'n.'}],
  ['miss', {meaning:'失误',pos:'n.'}],
  ['mix', {meaning:'混合物',pos:'n.'}],
  ['mixed', {meaning:'混合的',pos:'n.'}],
  ['mob', {meaning:'暴民',pos:'n.'}],
  ['model', {meaning:'模型',pos:'n.'}],
  ['modern', {meaning:'现代人',pos:'n.'}],
  ['mom', {meaning:'妈妈',pos:'n.'}],
  ['moment', {meaning:'片刻',pos:'n.'}],
  ['money', {meaning:'金钱',pos:'n.'}],
  ['month', {meaning:'月\n月',pos:'n.'}],
  ['mood', {meaning:'心情',pos:'n.'}],
  ['moon', {meaning:'月亮',pos:'n.'}],
  ['mop', {meaning:'拖把',pos:'n.'}],
  ['moral', {meaning:'道德',pos:'n.'}],
  ['more', {meaning:'更多\na. 多的',pos:'n.'}],
  ['morning', {meaning:'早晨',pos:'n.'}],
  ['most', {meaning:'最多',pos:'n.'}],
  ['mostly', {meaning:'大概',pos:'n.'}],
  ['mother', {meaning:'母亲',pos:'n.'}],
  ['motor', {meaning:'马达',pos:'n.'}],
  ['mount', {meaning:'乘骑用马',pos:'n.'}],
  ['mouse', {meaning:'老鼠',pos:'n.'}],
  ['mouth', {meaning:'嘴',pos:'n.'}],
  ['move', {meaning:'移动',pos:'n.'}],
  ['movement', {meaning:'运动',pos:'n.'}],
  ['movie', {meaning:'电影',pos:'n.'}],
  ['mow', {meaning:'草堆',pos:'n.'}],
  ['mrs', {meaning:'太太',pos:'n.'}],
  ['much', {meaning:'大量',pos:'n.'}],
  ['mud', {meaning:'泥',pos:'n.'}],
  ['mug', {meaning:'有柄大杯',pos:'n.'}],
  ['mum', {meaning:'菊花',pos:'n.'}],
  ['murder', {meaning:'谋杀\nvt. 谋杀',pos:'n.'}],
  ['museum', {meaning:'博物馆',pos:'n.'}],
  ['music', {meaning:'音乐',pos:'n.'}],
  ['must', {meaning:'必须',pos:'n.'}],
  ['myself', {meaning:'我自己',pos:'n.'}],
  ['myth', {meaning:'神话',pos:'n.'}],
  ['nag', {meaning:'老马',pos:'n.'}],
  ['nail', {meaning:'钉子',pos:'n.'}],
  ['naked', {meaning:'裸体的',pos:'n.'}],
  ['name', {meaning:'名字',pos:'n.'}],
  ['nap', {meaning:'小睡',pos:'n.'}],
  ['narrow', {meaning:'狭窄部分',pos:'n.'}],
  ['nation', {meaning:'国家',pos:'n.'}],
  ['national', {meaning:'国家的',pos:'n.'}],
  ['natural', {meaning:'白痴\na. 自然的',pos:'n.'}],
  ['nature', {meaning:'自然',pos:'n.'}],
  ['navy', {meaning:'海军',pos:'n.'}],
  ['near', {meaning:'近的',pos:'n.'}],
  ['nearly', {meaning:'几乎',pos:'n.'}],
  ['neat', {meaning:'整洁的',pos:'n.'}],
  ['neck', {meaning:'脖子',pos:'n.'}],
  ['need', {meaning:'需要',pos:'n.'}],
  ['nerve', {meaning:'精神',pos:'n.'}],
  ['nest', {meaning:'巢',pos:'n.'}],
  ['net', {meaning:'网',pos:'n.'}],
  ['network', {meaning:'网络',pos:'n.'}],
  ['never', {meaning:'从不',pos:'n.'}],
  ['new', {meaning:'新的',pos:'n.'}],
  ['newly', {meaning:'重新',pos:'n.'}],
  ['news', {meaning:'新闻',pos:'n.'}],
  ['next', {meaning:'下一个\na. 下一个的',pos:'n.'}],
  ['nice', {meaning:'美好的',pos:'n.'}],
  ['night', {meaning:'夜',pos:'n.'}],
  ['nine', {meaning:'九',pos:'n.'}],
  ['nip', {meaning:'捏',pos:'n.'}],
  ['nobody', {meaning:'小人物',pos:'n.'}],
  ['nod', {meaning:'点头',pos:'n.'}],
  ['noise', {meaning:'噪音',pos:'n.'}],
  ['none', {meaning:'一点也不',pos:'n.'}],
  ['nor', {meaning:'也不',pos:'n.'}],
  ['normal', {meaning:'常态',pos:'n.'}],
  ['north', {meaning:'北方',pos:'n.'}],
  ['nose', {meaning:'鼻子',pos:'n.'}],
  ['not', {meaning:'不',pos:'n.'}],
  ['note', {meaning:'笔记',pos:'n.'}],
  ['nothing', {meaning:'无',pos:'n.'}],
  ['notice', {meaning:'注意',pos:'n.'}],
  ['novel', {meaning:'小说',pos:'n.'}],
  ['now', {meaning:'现在',pos:'n.'}],
  ['number', {meaning:'数',pos:'n.'}],
  ['nun', {meaning:'修女',pos:'n.'}],
  ['nurse', {meaning:'护士',pos:'n.'}],
  ['nut', {meaning:'坚果',pos:'n.'}],
  ['oak', {meaning:'橡树',pos:'n.'}],
  ['oar', {meaning:'桨',pos:'n.'}],
  ['obey', {meaning:'服从',pos:'n.'}],
  ['object', {meaning:'物体',pos:'n.'}],
  ['occupy', {meaning:'占领',pos:'n.'}],
  ['occur', {meaning:'发生',pos:'n.'}],
  ['ocean', {meaning:'海洋',pos:'n.'}],
  ['odd', {meaning:'奇数的',pos:'n.'}],
  ['off', {meaning:'关着的',pos:'n.'}],
  ['offer', {meaning:'给予(物)',pos:'n.'}],
  ['office', {meaning:'办公室',pos:'n.'}],
  ['officer', {meaning:'军官',pos:'n.'}],
  ['official', {meaning:'官员',pos:'n.'}],
  ['often', {meaning:'时常',pos:'n.'}],
  ['oil', {meaning:'油',pos:'n.'}],
  ['okay', {meaning:'好',pos:'n.'}],
  ['old', {meaning:'以前',pos:'n.'}],
  ['once', {meaning:'一次',pos:'n.'}],
  ['one', {meaning:'一(个)\npron. 一',pos:'n.'}],
  ['onion', {meaning:'洋葱\nvt. 因洋葱使掉泪',pos:'n.'}],
  ['only', {meaning:'唯一的',pos:'n.'}],
  ['onto', {meaning:'在...之上',pos:'n.'}],
  ['ooh', {meaning:'（表示惊异、热心、高兴或不悦的叫声）哦！',pos:'n.'}],
  ['open', {meaning:'公开',pos:'n.'}],
  ['operate', {meaning:'操作',pos:'n.'}],
  ['operation', {meaning:'操作',pos:'n.'}],
  ['opt', {meaning:'选择',pos:'n.'}],
  ['option', {meaning:'选择权',pos:'n.'}],
  ['order', {meaning:'次序',pos:'n.'}],
  ['ore', {meaning:'矿石\n矿',pos:'n.'}],
  ['organ', {meaning:'风琴',pos:'n.'}],
  ['other', {meaning:'其他的',pos:'n.'}],
  ['our', {meaning:'我们的',pos:'n.'}],
  ['ours', {meaning:'我们的',pos:'n.'}],
  ['out', {meaning:'外面的',pos:'n.'}],
  ['outer', {meaning:'外部的',pos:'n.'}],
  ['outside', {meaning:'外面',pos:'n.'}],
  ['oven', {meaning:'烤箱',pos:'n.'}],
  ['over', {meaning:'结束',pos:'n.'}],
  ['owe', {meaning:'亏欠',pos:'n.'}],
  ['owl', {meaning:'猫头鹰\n走私',pos:'n.'}],
  ['own', {meaning:'自己的\na. 自己的',pos:'n.'}],
  ['owner', {meaning:'拥有者',pos:'n.'}],
  ['pace', {meaning:'速度',pos:'n.'}],
  ['pack', {meaning:'包裹',pos:'n.'}],
  ['pad', {meaning:'填补',pos:'n.'}],
  ['page', {meaning:'页',pos:'n.'}],
  ['pain', {meaning:'痛苦',pos:'n.'}],
  ['paint', {meaning:'油漆',pos:'n.'}],
  ['pair', {meaning:'一双',pos:'n.'}],
  ['pal', {meaning:'朋友',pos:'n.'}],
  ['pale', {meaning:'栅栏',pos:'n.'}],
  ['pan', {meaning:'平锅',pos:'n.'}],
  ['panel', {meaning:'嵌板',pos:'n.'}],
  ['paper', {meaning:'纸',pos:'n.'}],
  ['par', {meaning:'标准',pos:'n.'}],
  ['parent', {meaning:'父母',pos:'n.'}],
  ['park', {meaning:'公园',pos:'n.'}],
  ['part', {meaning:'部分',pos:'n.'}],
  ['party', {meaning:'宴会',pos:'n.'}],
  ['pass', {meaning:'经过',pos:'n.'}],
  ['past', {meaning:'过去',pos:'n.'}],
  ['pat', {meaning:'轻拍\nv. 轻拍\nadv. 适时',pos:'n.'}],
  ['path', {meaning:'路径',pos:'n.'}],
  ['patient', {meaning:'病人',pos:'n.'}],
  ['pause', {meaning:'暂停',pos:'n.'}],
  ['paw', {meaning:'爪\nv. 以蹄扒地',pos:'n.'}],
  ['pay', {meaning:'薪资',pos:'n.'}],
  ['pea', {meaning:'豌豆',pos:'n.'}],
  ['peace', {meaning:'和平',pos:'n.'}],
  ['peak', {meaning:'山峰',pos:'n.'}],
  ['pee', {meaning:'(英)便士',pos:'n.'}],
  ['peer', {meaning:'同等的人',pos:'n.'}],
  ['peg', {meaning:'钉',pos:'n.'}],
  ['pen', {meaning:'钢笔',pos:'n.'}],
  ['people', {meaning:'人',pos:'n.'}],
  ['pep', {meaning:'活力',pos:'n.'}],
  ['per', {meaning:'每一',pos:'n.'}],
  ['perhaps', {meaning:'也许',pos:'n.'}],
  ['period', {meaning:'时期',pos:'n.'}],
  ['person', {meaning:'人',pos:'n.'}],
  ['personal', {meaning:'私人的',pos:'n.'}],
  ['pet', {meaning:'宠物',pos:'n.'}],
  ['pew', {meaning:'教堂长椅',pos:'n.'}],
  ['phase', {meaning:'时期',pos:'n.'}],
  ['phd', {meaning:'哲学博士学位（Doctor of Philosophy）',pos:'n.'}],
  ['phone', {meaning:'电话',pos:'n.'}],
  ['physical', {meaning:'身体的',pos:'n.'}],
  ['piano', {meaning:'钢琴',pos:'n.'}],
  ['pick', {meaning:'精选',pos:'n.'}],
  ['picture', {meaning:'图画',pos:'n.'}],
  ['pie', {meaning:'馅饼',pos:'n.'}],
  ['piece', {meaning:'块',pos:'n.'}],
  ['pig', {meaning:'猪',pos:'n.'}],
  ['pile', {meaning:'堆',pos:'n.'}],
  ['pill', {meaning:'药丸',pos:'n.'}],
  ['pilot', {meaning:'飞行员',pos:'n.'}],
  ['pin', {meaning:'大头针',pos:'n.'}],
  ['pink', {meaning:'粉红色',pos:'n.'}],
  ['pint', {meaning:'品脱(干量或液量的单位)\n量磅',pos:'n.'}],
  ['pipe', {meaning:'管',pos:'n.'}],
  ['pit', {meaning:'深坑',pos:'n.'}],
  ['pitch', {meaning:'程度',pos:'n.'}],
  ['pity', {meaning:'遗憾',pos:'n.'}],
  ['place', {meaning:'地方',pos:'n.'}],
  ['plain', {meaning:'平原',pos:'n.'}],
  ['plan', {meaning:'计划',pos:'n.'}],
  ['plane', {meaning:'平面',pos:'n.'}],
  ['plant', {meaning:'植物',pos:'n.'}],
  ['plate', {meaning:'碟',pos:'n.'}],
  ['play', {meaning:'游戏',pos:'n.'}],
  ['player', {meaning:'竞赛者',pos:'n.'}],
  ['please', {meaning:'请\nvt. 使高兴',pos:'n.'}],
  ['plot', {meaning:'小块土地',pos:'n.'}],
  ['plug', {meaning:'塞子',pos:'n.'}],
  ['plus', {meaning:'加上',pos:'n.'}],
  ['ply', {meaning:'厚度',pos:'n.'}],
  ['pod', {meaning:'豆荚',pos:'n.'}],
  ['poem', {meaning:'诗',pos:'n.'}],
  ['poet', {meaning:'诗人',pos:'n.'}],
  ['point', {meaning:'点',pos:'n.'}],
  ['pole', {meaning:'波兰人',pos:'n.'}],
  ['police', {meaning:'警察',pos:'n.'}],
  ['policy', {meaning:'政策',pos:'n.'}],
  ['political', {meaning:'政治的',pos:'n.'}],
  ['poll', {meaning:'投票',pos:'n.'}],
  ['pool', {meaning:'池',pos:'n.'}],
  ['poor', {meaning:'贫穷的',pos:'n.'}],
  ['pop', {meaning:'砰然声',pos:'n.'}],
  ['popular', {meaning:'通俗的',pos:'n.'}],
  ['port', {meaning:'港口',pos:'n.'}],
  ['pose', {meaning:'姿势',pos:'n.'}],
  ['position', {meaning:'位置',pos:'n.'}],
  ['possible', {meaning:'可能的',pos:'n.'}],
  ['post', {meaning:'柱',pos:'n.'}],
  ['pot', {meaning:'盆',pos:'n.'}],
  ['pound', {meaning:'磅',pos:'n.'}],
  ['pour', {meaning:'流出',pos:'n.'}],
  ['power', {meaning:'力',pos:'n.'}],
  ['practice', {meaning:'实践',pos:'n.'}],
  ['prefer', {meaning:'宁可',pos:'n.'}],
  ['prepare', {meaning:'准备',pos:'n.'}],
  ['president', {meaning:'总统',pos:'n.'}],
  ['press', {meaning:'压',pos:'n.'}],
  ['pressure', {meaning:'压',pos:'n.'}],
  ['pretty', {meaning:'漂亮的',pos:'n.'}],
  ['price', {meaning:'价格',pos:'n.'}],
  ['pride', {meaning:'骄傲',pos:'n.'}],
  ['prince', {meaning:'王子',pos:'n.'}],
  ['print', {meaning:'打印',pos:'n.'}],
  ['prior', {meaning:'更重要的',pos:'n.'}],
  ['prison', {meaning:'监狱',pos:'n.'}],
  ['private', {meaning:'私人的',pos:'n.'}],
  ['prize', {meaning:'奖赏',pos:'n.'}],
  ['pro', {meaning:'正面地\n可编程远程操作',pos:'n.'}],
  ['probably', {meaning:'大概',pos:'n.'}],
  ['problem', {meaning:'问题',pos:'n.'}],
  ['process', {meaning:'程序',pos:'n.'}],
  ['produce', {meaning:'生产品',pos:'n.'}],
  ['product', {meaning:'产品',pos:'n.'}],
  ['professor', {meaning:'教授',pos:'n.'}],
  ['profit', {meaning:'利润',pos:'n.'}],
  ['program', {meaning:'节目',pos:'n.'}],
  ['project', {meaning:'计划',pos:'n.'}],
  ['proof', {meaning:'证据',pos:'n.'}],
  ['proper', {meaning:'适当的',pos:'n.'}],
  ['protect', {meaning:'防卫',pos:'n.'}],
  ['proud', {meaning:'骄傲的',pos:'n.'}],
  ['prove', {meaning:'证明',pos:'n.'}],
  ['provide', {meaning:'提供',pos:'n.'}],
  ['pry', {meaning:'杠杆',pos:'n.'}],
  ['pub', {meaning:'酒馆',pos:'n.'}],
  ['public', {meaning:'公众',pos:'n.'}],
  ['pull', {meaning:'拉',pos:'n.'}],
  ['pump', {meaning:'抽水机',pos:'n.'}],
  ['pun', {meaning:'双关语',pos:'n.'}],
  ['punch', {meaning:'打洞器',pos:'n.'}],
  ['pup', {meaning:'小狗',pos:'n.'}],
  ['pupil', {meaning:'学生',pos:'n.'}],
  ['pure', {meaning:'纯的',pos:'n.'}],
  ['push', {meaning:'推',pos:'n.'}],
  ['put', {meaning:'放',pos:'n.'}],
  ['quality', {meaning:'品质',pos:'n.'}],
  ['question', {meaning:'问题',pos:'n.'}],
  ['quick', {meaning:'快的',pos:'n.'}],
  ['quiet', {meaning:'安静',pos:'n.'}],
  ['quit', {meaning:'离开',pos:'n.'}],
  ['quite', {meaning:'相当',pos:'n.'}],
  ['quote', {meaning:'引用\nvt. 引述',pos:'n.'}],
  ['race', {meaning:'种族',pos:'n.'}],
  ['radio', {meaning:'无线电',pos:'n.'}],
  ['rag', {meaning:'碎布',pos:'n.'}],
  ['rage', {meaning:'愤怒',pos:'n.'}],
  ['raid', {meaning:'袭击',pos:'n.'}],
  ['rail', {meaning:'横杆',pos:'n.'}],
  ['rain', {meaning:'雨',pos:'n.'}],
  ['raise', {meaning:'上升',pos:'n.'}],
  ['ram', {meaning:'公羊',pos:'n.'}],
  ['range', {meaning:'排',pos:'n.'}],
  ['rank', {meaning:'等级',pos:'n.'}],
  ['rap', {meaning:'轻敲',pos:'n.'}],
  ['rape', {meaning:'抢夺',pos:'n.'}],
  ['rapid', {meaning:'迅速的',pos:'n.'}],
  ['rare', {meaning:'稀罕的',pos:'n.'}],
  ['rat', {meaning:'鼠',pos:'n.'}],
  ['rate', {meaning:'比率',pos:'n.'}],
  ['rather', {meaning:'宁可',pos:'n.'}],
  ['raw', {meaning:'擦伤处',pos:'n.'}],
  ['ray', {meaning:'光线',pos:'n.'}],
  ['reach', {meaning:'伸出',pos:'n.'}],
  ['react', {meaning:'起反应',pos:'n.'}],
  ['read', {meaning:'读',pos:'n.'}],
  ['reader', {meaning:'读者',pos:'n.'}],
  ['ready', {meaning:'预备好的状态',pos:'n.'}],
  ['real', {meaning:'真的',pos:'n.'}],
  ['realize', {meaning:'了解',pos:'n.'}],
  ['really', {meaning:'实际上',pos:'n.'}],
  ['rear', {meaning:'后面',pos:'n.'}],
  ['reason', {meaning:'理由',pos:'n.'}],
  ['recall', {meaning:'回忆',pos:'n.'}],
  ['receive', {meaning:'收到',pos:'n.'}],
  ['recent', {meaning:'最近的',pos:'n.'}],
  ['recently', {meaning:'最近',pos:'n.'}],
  ['recognize', {meaning:'认出',pos:'n.'}],
  ['record', {meaning:'记录',pos:'n.'}],
  ['red', {meaning:'红的',pos:'n.'}],
  ['reduce', {meaning:'减少',pos:'n.'}],
  ['reform', {meaning:'改革',pos:'n.'}],
  ['refuse', {meaning:'拒绝',pos:'n.'}],
  ['regard', {meaning:'关心',pos:'n.'}],
  ['region', {meaning:'区域',pos:'n.'}],
  ['reject', {meaning:'被拒之人',pos:'n.'}],
  ['relate', {meaning:'讲',pos:'n.'}],
  ['relax', {meaning:'放松',pos:'n.'}],
  ['release', {meaning:'释放',pos:'n.'}],
  ['relief', {meaning:'减轻',pos:'n.'}],
  ['religious', {meaning:'宗教性的',pos:'n.'}],
  ['rely', {meaning:'信赖',pos:'n.'}],
  ['remain', {meaning:'保持',pos:'n.'}],
  ['remember', {meaning:'记得',pos:'n.'}],
  ['remind', {meaning:'提醒',pos:'n.'}],
  ['remove', {meaning:'移动',pos:'n.'}],
  ['rent', {meaning:'租金',pos:'n.'}],
  ['rep', {meaning:'棱纹平布',pos:'n.'}],
  ['repeat', {meaning:'重复',pos:'n.'}],
  ['reply', {meaning:'答复',pos:'n.'}],
  ['report', {meaning:'报告',pos:'n.'}],
  ['represent', {meaning:'表现',pos:'n.'}],
  ['require', {meaning:'需要',pos:'n.'}],
  ['research', {meaning:'研究',pos:'n.'}],
  ['resource', {meaning:'资源',pos:'n.'}],
  ['respond', {meaning:'以...回答\nvi. 回答',pos:'n.'}],
  ['response', {meaning:'反应',pos:'n.'}],
  ['rest', {meaning:'休息',pos:'n.'}],
  ['result', {meaning:'结果',pos:'n.'}],
  ['return', {meaning:'回来',pos:'n.'}],
  ['reveal', {meaning:'露出',pos:'n.'}],
  ['review', {meaning:'检讨',pos:'n.'}],
  ['rib', {meaning:'肋骨',pos:'n.'}],
  ['rice', {meaning:'米',pos:'n.'}],
  ['rich', {meaning:'富裕的',pos:'n.'}],
  ['rid', {meaning:'免除',pos:'n.'}],
  ['ride', {meaning:'骑马',pos:'n.'}],
  ['rider', {meaning:'骑手',pos:'n.'}],
  ['rig', {meaning:'装备',pos:'n.'}],
  ['right', {meaning:'权利',pos:'n.'}],
  ['rim', {meaning:'边',pos:'n.'}],
  ['ring', {meaning:'环',pos:'n.'}],
  ['riot', {meaning:'暴动',pos:'n.'}],
  ['rip', {meaning:'裂痕',pos:'n.'}],
  ['rise', {meaning:'上升',pos:'n.'}],
  ['risk', {meaning:'冒险',pos:'n.'}],
  ['rival', {meaning:'对手',pos:'n.'}],
  ['river', {meaning:'河',pos:'n.'}],
  ['rna', {meaning:'核糖核酸',pos:'n.'}],
  ['road', {meaning:'路',pos:'n.'}],
  ['rob', {meaning:'抢夺',pos:'n.'}],
  ['rock', {meaning:'岩石',pos:'n.'}],
  ['rod', {meaning:'竿',pos:'n.'}],
  ['role', {meaning:'角色',pos:'n.'}],
  ['roll', {meaning:'卷',pos:'n.'}],
  ['roof', {meaning:'屋顶',pos:'n.'}],
  ['room', {meaning:'房间',pos:'n.'}],
  ['root', {meaning:'根',pos:'n.'}],
  ['rope', {meaning:'绳',pos:'n.'}],
  ['rot', {meaning:'腐烂',pos:'n.'}],
  ['rough', {meaning:'粗糙的东西',pos:'n.'}],
  ['round', {meaning:'圆',pos:'n.'}],
  ['route', {meaning:'路径',pos:'n.'}],
  ['row', {meaning:'排',pos:'n.'}],
  ['royal', {meaning:'王室',pos:'n.'}],
  ['rub', {meaning:'摩擦',pos:'n.'}],
  ['rude', {meaning:'粗鲁无礼的',pos:'n.'}],
  ['rug', {meaning:'小块地毯',pos:'n.'}],
  ['ruin', {meaning:'毁灭',pos:'n.'}],
  ['rule', {meaning:'规则',pos:'n.'}],
  ['rum', {meaning:'朗姆酒\na. 古怪的',pos:'n.'}],
  ['run', {meaning:'跑',pos:'n.'}],
  ['rural', {meaning:'乡下的',pos:'n.'}],
  ['rush', {meaning:'匆促',pos:'n.'}],
  ['rut', {meaning:'辙迹',pos:'n.'}],
  ['sack', {meaning:'麻布袋',pos:'n.'}],
  ['sad', {meaning:'忧愁的',pos:'n.'}],
  ['safe', {meaning:'保险箱',pos:'n.'}],
  ['safety', {meaning:'安全',pos:'n.'}],
  ['sag', {meaning:'下垂',pos:'n.'}],
  ['sail', {meaning:'帆',pos:'n.'}],
  ['sake', {meaning:'目的',pos:'n.'}],
  ['salad', {meaning:'色拉',pos:'n.'}],
  ['sale', {meaning:'出售',pos:'n.'}],
  ['salt', {meaning:'盐',pos:'n.'}],
  ['same', {meaning:'相同的',pos:'n.'}],
  ['sample', {meaning:'样品',pos:'n.'}],
  ['sand', {meaning:'沙',pos:'n.'}],
  ['sap', {meaning:'树液',pos:'n.'}],
  ['sauce', {meaning:'酱油',pos:'n.'}],
  ['save', {meaning:'救球\nvt. 解救',pos:'n.'}],
  ['saw', {meaning:'锯子',pos:'n.'}],
  ['say', {meaning:'说',pos:'n.'}],
  ['scale', {meaning:'刻度',pos:'n.'}],
  ['scare', {meaning:'惊吓',pos:'n.'}],
  ['scene', {meaning:'场',pos:'n.'}],
  ['scheme', {meaning:'方案',pos:'n.'}],
  ['school', {meaning:'学校',pos:'n.'}],
  ['science', {meaning:'科学',pos:'n.'}],
  ['score', {meaning:'得分',pos:'n.'}],
  ['screen', {meaning:'幕',pos:'n.'}],
  ['screw', {meaning:'螺旋',pos:'n.'}],
  ['sea', {meaning:'海',pos:'n.'}],
  ['seal', {meaning:'印章',pos:'n.'}],
  ['search', {meaning:'搜寻',pos:'n.'}],
  ['season', {meaning:'季节',pos:'n.'}],
  ['seat', {meaning:'座',pos:'n.'}],
  ['second', {meaning:'秒',pos:'n.'}],
  ['secret', {meaning:'秘密',pos:'n.'}],
  ['section', {meaning:'区段',pos:'n.'}],
  ['sector', {meaning:'扇形',pos:'n.'}],
  ['secure', {meaning:'无虑的',pos:'n.'}],
  ['security', {meaning:'安全',pos:'n.'}],
  ['see', {meaning:'看见',pos:'n.'}],
  ['seed', {meaning:'种子',pos:'n.'}],
  ['seek', {meaning:'寻求',pos:'n.'}],
  ['seem', {meaning:'象是',pos:'n.'}],
  ['self', {meaning:'自己',pos:'n.'}],
  ['sell', {meaning:'卖',pos:'n.'}],
  ['send', {meaning:'发送',pos:'n.'}],
  ['sense', {meaning:'感应',pos:'n.'}],
  ['series', {meaning:'串联',pos:'n.'}],
  ['serious', {meaning:'严肃的',pos:'n.'}],
  ['serve', {meaning:'可作...用',pos:'n.'}],
  ['service', {meaning:'服务',pos:'n.'}],
  ['set', {meaning:'日落',pos:'n.'}],
  ['settle', {meaning:'有背长椅\nvt. 决定',pos:'n.'}],
  ['several', {meaning:'几个的',pos:'n.'}],
  ['severe', {meaning:'严格的',pos:'n.'}],
  ['sew', {meaning:'缝纫',pos:'n.'}],
  ['sex', {meaning:'性别',pos:'n.'}],
  ['sexual', {meaning:'性的',pos:'n.'}],
  ['shade', {meaning:'荫',pos:'n.'}],
  ['shake', {meaning:'摇动',pos:'n.'}],
  ['shall', {meaning:'aux. 将',pos:'n.'}],
  ['shame', {meaning:'羞耻',pos:'n.'}],
  ['shape', {meaning:'形状',pos:'n.'}],
  ['share', {meaning:'部分',pos:'n.'}],
  ['sharp', {meaning:'半升音调',pos:'n.'}],
  ['she', {meaning:'她',pos:'n.'}],
  ['shed', {meaning:'车棚',pos:'n.'}],
  ['sheep', {meaning:'羊',pos:'n.'}],
  ['sheet', {meaning:'床单',pos:'n.'}],
  ['shelf', {meaning:'架子',pos:'n.'}],
  ['shell', {meaning:'贝壳',pos:'n.'}],
  ['shift', {meaning:'变化',pos:'n.'}],
  ['shine', {meaning:'光泽',pos:'n.'}],
  ['ship', {meaning:'船',pos:'n.'}],
  ['shirt', {meaning:'衬衫',pos:'n.'}],
  ['shock', {meaning:'震动',pos:'n.'}],
  ['shoe', {meaning:'鞋',pos:'n.'}],
  ['shoot', {meaning:'射击',pos:'n.'}],
  ['shop', {meaning:'商店',pos:'n.'}],
  ['short', {meaning:'短的',pos:'n.'}],
  ['shot', {meaning:'发射',pos:'n.'}],
  ['should', {meaning:'aux. 应该',pos:'n.'}],
  ['shout', {meaning:'呼喊',pos:'n.'}],
  ['show', {meaning:'显示',pos:'n.'}],
  ['shut', {meaning:'关闭\nvt. 关上',pos:'n.'}],
  ['shy', {meaning:'惊跳',pos:'n.'}],
  ['sic', {meaning:'原文如此',pos:'n.'}],
  ['sick', {meaning:'病人\na. 不舒服',pos:'n.'}],
  ['side', {meaning:'旁边',pos:'n.'}],
  ['sigh', {meaning:'叹息\nvi. 叹息',pos:'n.'}],
  ['sight', {meaning:'景观',pos:'n.'}],
  ['sign', {meaning:'符号',pos:'n.'}],
  ['silk', {meaning:'丝',pos:'n.'}],
  ['silly', {meaning:'愚蠢的',pos:'n.'}],
  ['similar', {meaning:'相似的',pos:'n.'}],
  ['simple', {meaning:'简单的',pos:'n.'}],
  ['simply', {meaning:'简单地',pos:'n.'}],
  ['sin', {meaning:'罪',pos:'n.'}],
  ['since', {meaning:'自...以后',pos:'n.'}],
  ['sing', {meaning:'唱',pos:'n.'}],
  ['single', {meaning:'单身的',pos:'n.'}],
  ['sink', {meaning:'藏垢的场所',pos:'n.'}],
  ['sip', {meaning:'啜饮',pos:'n.'}],
  ['sir', {meaning:'先生',pos:'n.'}],
  ['sister', {meaning:'姐妹',pos:'n.'}],
  ['sit', {meaning:'坐',pos:'n.'}],
  ['site', {meaning:'位置',pos:'n.'}],
  ['situation', {meaning:'情形',pos:'n.'}],
  ['six', {meaning:'六',pos:'n.'}],
  ['size', {meaning:'大小',pos:'n.'}],
  ['ski', {meaning:'滑雪橇\nvi. 滑雪',pos:'n.'}],
  ['skill', {meaning:'技术',pos:'n.'}],
  ['skin', {meaning:'皮肤',pos:'n.'}],
  ['skirt', {meaning:'裙子',pos:'n.'}],
  ['sky', {meaning:'天空',pos:'n.'}],
  ['sleep', {meaning:'睡眠',pos:'n.'}],
  ['slice', {meaning:'薄的切片',pos:'n.'}],
  ['slide', {meaning:'滑',pos:'n.'}],
  ['slip', {meaning:'滑',pos:'n.'}],
  ['slope', {meaning:'倾斜',pos:'n.'}],
  ['slow', {meaning:'慢的',pos:'n.'}],
  ['sly', {meaning:'狡猾的',pos:'n.'}],
  ['small', {meaning:'小的',pos:'n.'}],
  ['smart', {meaning:'聪明的',pos:'n.'}],
  ['smash', {meaning:'打碎',pos:'n.'}],
  ['smell', {meaning:'味道',pos:'n.'}],
  ['smile', {meaning:'微笑',pos:'n.'}],
  ['smoke', {meaning:'烟',pos:'n.'}],
  ['snake', {meaning:'蛇',pos:'n.'}],
  ['snap', {meaning:'使突然中断',pos:'n.'}],
  ['snow', {meaning:'雪',pos:'n.'}],
  ['soap', {meaning:'肥皂',pos:'n.'}],
  ['sob', {meaning:'啜泣',pos:'n.'}],
  ['social', {meaning:'社会的',pos:'n.'}],
  ['society', {meaning:'社会；社交界；交往；社团',pos:'n.'}],
  ['sock', {meaning:'短袜',pos:'n.'}],
  ['soft', {meaning:'软的',pos:'n.'}],
  ['soil', {meaning:'土壤',pos:'n.'}],
  ['solid', {meaning:'固体\na. 坚硬的',pos:'n.'}],
  ['solve', {meaning:'解决',pos:'n.'}],
  ['some', {meaning:'一些',pos:'n.'}],
  ['something', {meaning:'某事',pos:'n.'}],
  ['sometimes', {meaning:'有时',pos:'n.'}],
  ['son', {meaning:'儿子',pos:'n.'}],
  ['song', {meaning:'歌',pos:'n.'}],
  ['soon', {meaning:'不久',pos:'n.'}],
  ['sore', {meaning:'悲伤的',pos:'n.'}],
  ['sorry', {meaning:'难过的',pos:'n.'}],
  ['sort', {meaning:'种类',pos:'n.'}],
  ['soul', {meaning:'灵魂',pos:'n.'}],
  ['sound', {meaning:'声音',pos:'n.'}],
  ['soup', {meaning:'汤',pos:'n.'}],
  ['sour', {meaning:'酸的',pos:'n.'}],
  ['source', {meaning:'来源',pos:'n.'}],
  ['south', {meaning:'南方',pos:'n.'}],
  ['sow', {meaning:'母猪',pos:'n.'}],
  ['soy', {meaning:'酱油',pos:'n.'}],
  ['spa', {meaning:'矿泉',pos:'n.'}],
  ['space', {meaning:'位置',pos:'n.'}],
  ['spare', {meaning:'剩余',pos:'n.'}],
  ['speak', {meaning:'说',pos:'n.'}],
  ['special', {meaning:'专辑',pos:'n.'}],
  ['speech', {meaning:'演讲',pos:'n.'}],
  ['speed', {meaning:'速率',pos:'n.'}],
  ['spell', {meaning:'符咒',pos:'n.'}],
  ['spend', {meaning:'花费',pos:'n.'}],
  ['spin', {meaning:'旋转',pos:'n.'}],
  ['spirit', {meaning:'精神',pos:'n.'}],
  ['spite', {meaning:'恶意',pos:'n.'}],
  ['split', {meaning:'劈开',pos:'n.'}],
  ['spoon', {meaning:'匙',pos:'n.'}],
  ['sport', {meaning:'运动',pos:'n.'}],
  ['spot', {meaning:'污点',pos:'n.'}],
  ['spray', {meaning:'水沫',pos:'n.'}],
  ['spread', {meaning:'传播',pos:'n.'}],
  ['spring', {meaning:'春天',pos:'n.'}],
  ['spy', {meaning:'间谍',pos:'n.'}],
  ['square', {meaning:'正方形',pos:'n.'}],
  ['stable', {meaning:'马房',pos:'n.'}],
  ['staff', {meaning:'全体人员',pos:'n.'}],
  ['stage', {meaning:'阶段',pos:'n.'}],
  ['stair', {meaning:'梯级',pos:'n.'}],
  ['stamp', {meaning:'印',pos:'n.'}],
  ['stand', {meaning:'站立',pos:'n.'}],
  ['standard', {meaning:'标准',pos:'n.'}],
  ['star', {meaning:'星',pos:'n.'}],
  ['stare', {meaning:'注视',pos:'n.'}],
  ['start', {meaning:'惊起',pos:'n.'}],
  ['state', {meaning:'州',pos:'n.'}],
  ['statement', {meaning:'陈述',pos:'n.'}],
  ['station', {meaning:'车站',pos:'n.'}],
  ['status', {meaning:'状态',pos:'n.'}],
  ['stay', {meaning:'停留',pos:'n.'}],
  ['steal', {meaning:'剽窃；偷偷地做；偷窃；vi. 窃取；偷偷地行动；偷垒；n.偷窃；便宜货；偷垒；断球',pos:'n.'}],
  ['steam', {meaning:'蒸汽',pos:'n.'}],
  ['steel', {meaning:'钢',pos:'n.'}],
  ['steep', {meaning:'浸渍',pos:'n.'}],
  ['steer', {meaning:'引导',pos:'n.'}],
  ['stem', {meaning:'茎',pos:'n.'}],
  ['step', {meaning:'步骤',pos:'n.'}],
  ['stick', {meaning:'棍',pos:'n.'}],
  ['stiff', {meaning:'坚硬的',pos:'n.'}],
  ['still', {meaning:'蒸馏室',pos:'n.'}],
  ['stir', {meaning:'骚动',pos:'n.'}],
  ['stock', {meaning:'树干',pos:'n.'}],
  ['stone', {meaning:'石头',pos:'n.'}],
  ['stop', {meaning:'停止',pos:'n.'}],
  ['store', {meaning:'商店',pos:'n.'}],
  ['storm', {meaning:'暴风雨',pos:'n.'}],
  ['story', {meaning:'故事',pos:'n.'}],
  ['strategy', {meaning:'战略',pos:'n.'}],
  ['street', {meaning:'街道',pos:'n.'}],
  ['stress', {meaning:'压力',pos:'n.'}],
  ['strike', {meaning:'罢工',pos:'n.'}],
  ['strip', {meaning:'长条',pos:'n.'}],
  ['strong', {meaning:'强壮的',pos:'n.'}],
  ['student', {meaning:'学生',pos:'n.'}],
  ['studio', {meaning:'工作室',pos:'n.'}],
  ['study', {meaning:'学习',pos:'n.'}],
  ['stuff', {meaning:'原料',pos:'n.'}],
  ['style', {meaning:'风格',pos:'n.'}],
  ['sub', {meaning:'补充人员',pos:'n.'}],
  ['subject', {meaning:'科目',pos:'n.'}],
  ['success', {meaning:'成功',pos:'n.'}],
  ['such', {meaning:'如此的',pos:'n.'}],
  ['suck', {meaning:'吸',pos:'n.'}],
  ['sue', {meaning:'控告',pos:'n.'}],
  ['suffer', {meaning:'遭受',pos:'n.'}],
  ['sugar', {meaning:'糖',pos:'n.'}],
  ['suggest', {meaning:'提议',pos:'n.'}],
  ['suit', {meaning:'套装',pos:'n.'}],
  ['sum', {meaning:'总数',pos:'n.'}],
  ['summer', {meaning:'夏季',pos:'n.'}],
  ['sun', {meaning:'太阳',pos:'n.'}],
  ['supply', {meaning:'补给',pos:'n.'}],
  ['support', {meaning:'支持',pos:'n.'}],
  ['sure', {meaning:'确信',pos:'n.'}],
  ['surprise', {meaning:'惊奇',pos:'n.'}],
  ['survey', {meaning:'纵览',pos:'n.'}],
  ['swear', {meaning:'发誓',pos:'n.'}],
  ['sweat', {meaning:'汗',pos:'n.'}],
  ['sweep', {meaning:'扫除',pos:'n.'}],
  ['sweet', {meaning:'甜蜜',pos:'n.'}],
  ['swim', {meaning:'游泳',pos:'n.'}],
  ['swing', {meaning:'摇摆',pos:'n.'}],
  ['system', {meaning:'系统',pos:'n.'}],
  ['tab', {meaning:'制表(键)',pos:'n.'}],
  ['table', {meaning:'桌子',pos:'n.'}],
  ['tag', {meaning:'标签',pos:'n.'}],
  ['tail', {meaning:'尾部',pos:'n.'}],
  ['take', {meaning:'拿',pos:'n.'}],
  ['tale', {meaning:'故事',pos:'n.'}],
  ['talk', {meaning:'谈话',pos:'n.'}],
  ['tall', {meaning:'高的',pos:'n.'}],
  ['tan', {meaning:'黄褐色',pos:'n.'}],
  ['tank', {meaning:'槽',pos:'n.'}],
  ['tap', {meaning:'轻打',pos:'n.'}],
  ['tape', {meaning:'带子',pos:'n.'}],
  ['tar', {meaning:'焦油',pos:'n.'}],
  ['target', {meaning:'目标',pos:'n.'}],
  ['task', {meaning:'工作',pos:'n.'}],
  ['taste', {meaning:'味道',pos:'n.'}],
  ['tax', {meaning:'税',pos:'n.'}],
  ['taxi', {meaning:'出租车\nvi. 乘出租车\nvt. 用出租车送',pos:'n.'}],
  ['tea', {meaning:'茶',pos:'n.'}],
  ['teach', {meaning:'教',pos:'n.'}],
  ['team', {meaning:'队',pos:'n.'}],
  ['tear', {meaning:'泪滴',pos:'n.'}],
  ['tee', {meaning:'T字形',pos:'n.'}],
  ['tell', {meaning:'告诉',pos:'n.'}],
  ['ten', {meaning:'十',pos:'n.'}],
  ['tend', {meaning:'走向',pos:'n.'}],
  ['tent', {meaning:'帐篷',pos:'n.'}],
  ['term', {meaning:'术语',pos:'n.'}],
  ['test', {meaning:'测试',pos:'n.'}],
  ['text', {meaning:'文本',pos:'n.'}],
  ['than', {meaning:'比',pos:'n.'}],
  ['thank', {meaning:'谢意',pos:'n.'}],
  ['that', {meaning:'那',pos:'n.'}],
  ['the', {meaning:'那',pos:'n.'}],
  ['their', {meaning:'他们的',pos:'n.'}],
  ['them', {meaning:'他们',pos:'n.'}],
  ['theme', {meaning:'主题',pos:'n.'}],
  ['then', {meaning:'然后',pos:'n.'}],
  ['theory', {meaning:'理论',pos:'n.'}],
  ['there', {meaning:'在那里',pos:'n.'}],
  ['they', {meaning:'他们',pos:'n.'}],
  ['thick', {meaning:'厚的',pos:'n.'}],
  ['thin', {meaning:'薄的',pos:'n.'}],
  ['thing', {meaning:'事物',pos:'n.'}],
  ['think', {meaning:'想',pos:'n.'}],
  ['this', {meaning:'这',pos:'n.'}],
  ['though', {meaning:'然而',pos:'n.'}],
  ['thought', {meaning:'想法',pos:'n.'}],
  ['threat', {meaning:'恐吓',pos:'n.'}],
  ['through', {meaning:'穿越',pos:'n.'}],
  ['throw', {meaning:'投',pos:'n.'}],
  ['thumb', {meaning:'拇指\nvt. 以拇指拨弄',pos:'n.'}],
  ['thus', {meaning:'如此',pos:'n.'}],
  ['thy', {meaning:'你的',pos:'n.'}],
  ['ticket', {meaning:'票',pos:'n.'}],
  ['tide', {meaning:'潮',pos:'n.'}],
  ['tidy', {meaning:'椅子的背罩',pos:'n.'}],
  ['tie', {meaning:'带子',pos:'n.'}],
  ['tight', {meaning:'紧的',pos:'n.'}],
  ['till', {meaning:'直到',pos:'n.'}],
  ['time', {meaning:'时间',pos:'n.'}],
  ['tin', {meaning:'锡',pos:'n.'}],
  ['tiny', {meaning:'很少的',pos:'n.'}],
  ['tip', {meaning:'顶',pos:'n.'}],
  ['tire', {meaning:'轮胎',pos:'n.'}],
  ['tired', {meaning:'疲累的',pos:'n.'}],
  ['tit', {meaning:'山雀',pos:'n.'}],
  ['title', {meaning:'头衔',pos:'n.'}],
  ['today', {meaning:'今天',pos:'n.'}],
  ['toe', {meaning:'足趾',pos:'n.'}],
  ['together', {meaning:'一起',pos:'n.'}],
  ['ton', {meaning:'吨\n吨',pos:'n.'}],
  ['tone', {meaning:'音调',pos:'n.'}],
  ['tonight', {meaning:'今晚',pos:'n.'}],
  ['too', {meaning:'也',pos:'n.'}],
  ['tool', {meaning:'工具',pos:'n.'}],
  ['tooth', {meaning:'牙齿',pos:'n.'}],
  ['top', {meaning:'顶部',pos:'n.'}],
  ['topic', {meaning:'主题',pos:'n.'}],
  ['total', {meaning:'全体的',pos:'n.'}],
  ['touch', {meaning:'触觉',pos:'n.'}],
  ['tough', {meaning:'恶棍\na. 强硬的',pos:'n.'}],
  ['tour', {meaning:'旅游',pos:'n.'}],
  ['tow', {meaning:'拖',pos:'n.'}],
  ['towards', {meaning:'向',pos:'n.'}],
  ['towel', {meaning:'手巾',pos:'n.'}],
  ['tower', {meaning:'塔',pos:'n.'}],
  ['town', {meaning:'城镇',pos:'n.'}],
  ['toy', {meaning:'玩具',pos:'n.'}],
  ['trace', {meaning:'痕迹',pos:'n.'}],
  ['track', {meaning:'轨迹',pos:'n.'}],
  ['trade', {meaning:'贸易',pos:'n.'}],
  ['train', {meaning:'火车',pos:'n.'}],
  ['trap', {meaning:'圈套',pos:'n.'}],
  ['travel', {meaning:'旅行',pos:'n.'}],
  ['treat', {meaning:'宴请',pos:'n.'}],
  ['treatment', {meaning:'治疗',pos:'n.'}],
  ['tree', {meaning:'树',pos:'n.'}],
  ['trend', {meaning:'趋势',pos:'n.'}],
  ['trial', {meaning:'审判',pos:'n.'}],
  ['trick', {meaning:'诡计',pos:'n.'}],
  ['trip', {meaning:'旅行',pos:'n.'}],
  ['truck', {meaning:'卡车',pos:'n.'}],
  ['true', {meaning:'真实的',pos:'n.'}],
  ['truly', {meaning:'真实地',pos:'n.'}],
  ['trust', {meaning:'信任',pos:'n.'}],
  ['truth', {meaning:'事实',pos:'n.'}],
  ['try', {meaning:'尝试',pos:'n.'}],
  ['tub', {meaning:'桶',pos:'n.'}],
  ['tube', {meaning:'管',pos:'n.'}],
  ['tug', {meaning:'用力拉',pos:'n.'}],
  ['tune', {meaning:'歌曲',pos:'n.'}],
  ['turn', {meaning:'转弯',pos:'n.'}],
  ['twice', {meaning:'两次',pos:'n.'}],
  ['twin', {meaning:'双胞胎中一人',pos:'n.'}],
  ['twist', {meaning:'一扭',pos:'n.'}],
  ['two', {meaning:'二',pos:'n.'}],
  ['type', {meaning:'类型',pos:'n.'}],
  ['tyre', {meaning:'轮胎\nvt. 装轮胎于',pos:'n.'}],
  ['ugly', {meaning:'丑陋的',pos:'n.'}],
  ['uncle', {meaning:'叔父',pos:'n.'}],
  ['under', {meaning:'在...之下',pos:'n.'}],
  ['undo', {meaning:'解开',pos:'n.'}],
  ['union', {meaning:'联盟',pos:'n.'}],
  ['unit', {meaning:'单位',pos:'n.'}],
  ['unite', {meaning:'联合',pos:'n.'}],
  ['united', {meaning:'联合的',pos:'n.'}],
  ['unless', {meaning:'除非\nprep. 除...之外',pos:'n.'}],
  ['until', {meaning:'直到',pos:'n.'}],
  ['upon', {meaning:'在...之上',pos:'n.'}],
  ['upper', {meaning:'上面的',pos:'n.'}],
  ['upset', {meaning:'弄翻的',pos:'n.'}],
  ['urban', {meaning:'都市的',pos:'n.'}],
  ['urge', {meaning:'冲动',pos:'n.'}],
  ['urn', {meaning:'瓮',pos:'n.'}],
  ['use', {meaning:'使用',pos:'n.'}],
  ['used', {meaning:'使用过的',pos:'n.'}],
  ['useful', {meaning:'有用的',pos:'n.'}],
  ['user', {meaning:'使用者\n用户',pos:'n.'}],
  ['usual', {meaning:'平常的',pos:'n.'}],
  ['usually', {meaning:'通常',pos:'n.'}],
  ['valid', {meaning:'有确实根据的',pos:'n.'}],
  ['value', {meaning:'价值',pos:'n.'}],
  ['van', {meaning:'货车',pos:'n.'}],
  ['various', {meaning:'不同的',pos:'n.'}],
  ['vary', {meaning:'改变',pos:'n.'}],
  ['vast', {meaning:'巨大的',pos:'n.'}],
  ['vat', {meaning:'大桶\nvt. 装入大桶',pos:'n.'}],
  ['very', {meaning:'真正的',pos:'n.'}],
  ['vet', {meaning:'兽医\nvi. 当兽医\nvt. 诊断',pos:'n.'}],
  ['via', {meaning:'经由',pos:'n.'}],
  ['victim', {meaning:'受害人',pos:'n.'}],
  ['video', {meaning:'影像',pos:'n.'}],
  ['vie', {meaning:'争',pos:'n.'}],
  ['view', {meaning:'视野',pos:'n.'}],
  ['vip', {meaning:'要人',pos:'n.'}],
  ['virus', {meaning:'病毒',pos:'n.'}],
  ['vision', {meaning:'视觉',pos:'n.'}],
  ['visit', {meaning:'拜访',pos:'n.'}],
  ['vital', {meaning:'生命的',pos:'n.'}],
  ['voice', {meaning:'声音',pos:'n.'}],
  ['volume', {meaning:'册',pos:'n.'}],
  ['vote', {meaning:'投票',pos:'n.'}],
  ['vow', {meaning:'誓约',pos:'n.'}],
  ['wad', {meaning:'小软团',pos:'n.'}],
  ['wag', {meaning:'摇摆',pos:'n.'}],
  ['wage', {meaning:'工资',pos:'n.'}],
  ['waist', {meaning:'腰部',pos:'n.'}],
  ['wait', {meaning:'等待',pos:'n.'}],
  ['wake', {meaning:'叫醒',pos:'n.'}],
  ['walk', {meaning:'走',pos:'n.'}],
  ['wall', {meaning:'墙',pos:'n.'}],
  ['wan', {meaning:'苍白的',pos:'n.'}],
  ['want', {meaning:'需要的东西',pos:'n.'}],
  ['war', {meaning:'战争',pos:'n.'}],
  ['warm', {meaning:'暖和的',pos:'n.'}],
  ['warn', {meaning:'警告',pos:'n.'}],
  ['wash', {meaning:'洗',pos:'n.'}],
  ['waste', {meaning:'浪费',pos:'n.'}],
  ['watch', {meaning:'观察',pos:'n.'}],
  ['water', {meaning:'水',pos:'n.'}],
  ['wave', {meaning:'波',pos:'n.'}],
  ['wax', {meaning:'蜡',pos:'n.'}],
  ['way', {meaning:'路',pos:'n.'}],
  ['weak', {meaning:'不牢固的',pos:'n.'}],
  ['weapon', {meaning:'武器',pos:'n.'}],
  ['wear', {meaning:'穿着',pos:'n.'}],
  ['web', {meaning:'网',pos:'n.'}],
  ['wed', {meaning:'与...结婚',pos:'n.'}],
  ['wee', {meaning:'很小的',pos:'n.'}],
  ['week', {meaning:'星期',pos:'n.'}],
  ['weigh', {meaning:'称...重量',pos:'n.'}],
  ['weight', {meaning:'重',pos:'n.'}],
  ['well', {meaning:'井',pos:'n.'}],
  ['west', {meaning:'西方',pos:'n.'}],
  ['wet', {meaning:'湿气',pos:'n.'}],
  ['what', {meaning:'什么\ninterj. 怎么',pos:'n.'}],
  ['whatever', {meaning:'无论什么',pos:'n.'}],
  ['wheel', {meaning:'轮子',pos:'n.'}],
  ['when', {meaning:'当...的时候\nadv. 何时',pos:'n.'}],
  ['where', {meaning:'在哪里\npron. 哪里\nn. 地点',pos:'n.'}],
  ['whether', {meaning:'是否',pos:'n.'}],
  ['which', {meaning:'哪一个',pos:'n.'}],
  ['while', {meaning:'一会儿',pos:'n.'}],
  ['whip', {meaning:'鞭子',pos:'n.'}],
  ['white', {meaning:'白色',pos:'n.'}],
  ['who', {meaning:'谁',pos:'n.'}],
  ['whole', {meaning:'全部',pos:'n.'}],
  ['whom', {meaning:'谁',pos:'n.'}],
  ['whose', {meaning:'谁的',pos:'n.'}],
  ['why', {meaning:'为什么\nn. 原因',pos:'n.'}],
  ['wide', {meaning:'宽的',pos:'n.'}],
  ['wife', {meaning:'妻子',pos:'n.'}],
  ['wig', {meaning:'假发',pos:'n.'}],
  ['wild', {meaning:'荒野',pos:'n.'}],
  ['will', {meaning:'意志',pos:'n.'}],
  ['win', {meaning:'赢得',pos:'n.'}],
  ['wind', {meaning:'风',pos:'n.'}],
  ['window', {meaning:'窗户',pos:'n.'}],
  ['wine', {meaning:'葡萄酒',pos:'n.'}],
  ['wing', {meaning:'翅膀',pos:'n.'}],
  ['winner', {meaning:'胜利者',pos:'n.'}],
  ['winter', {meaning:'冬季',pos:'n.'}],
  ['wipe', {meaning:'擦拭',pos:'n.'}],
  ['wire', {meaning:'电线',pos:'n.'}],
  ['wise', {meaning:'明智的',pos:'n.'}],
  ['wish', {meaning:'希望',pos:'n.'}],
  ['wit', {meaning:'机智',pos:'n.'}],
  ['with', {meaning:'和...在一起',pos:'n.'}],
  ['within', {meaning:'内部',pos:'n.'}],
  ['without', {meaning:'没有',pos:'n.'}],
  ['woe', {meaning:'悲哀',pos:'n.'}],
  ['woman', {meaning:'女人',pos:'n.'}],
  ['wonder', {meaning:'奇迹',pos:'n.'}],
  ['woo', {meaning:'追求',pos:'n.'}],
  ['wood', {meaning:'木材',pos:'n.'}],
  ['wool', {meaning:'羊毛',pos:'n.'}],
  ['word', {meaning:'话',pos:'n.'}],
  ['work', {meaning:'工作',pos:'n.'}],
  ['worker', {meaning:'工人',pos:'n.'}],
  ['working', {meaning:'工作',pos:'n.'}],
  ['world', {meaning:'世界',pos:'n.'}],
  ['worry', {meaning:'担心',pos:'n.'}],
  ['worth', {meaning:'价值',pos:'n.'}],
  ['would', {meaning:'aux. 将',pos:'n.'}],
  ['wound', {meaning:'创伤',pos:'n.'}],
  ['wow', {meaning:'(非正式)哇\nn. 巨大的成功',pos:'n.'}],
  ['wrap', {meaning:'外套',pos:'n.'}],
  ['wrist', {meaning:'手腕',pos:'n.'}],
  ['write', {meaning:'书写',pos:'n.'}],
  ['wrong', {meaning:'错误的',pos:'n.'}],
  ['wry', {meaning:'扭歪的',pos:'n.'}],
  ['yard', {meaning:'码',pos:'n.'}],
  ['yawn', {meaning:'哈欠\nvi. 打哈欠',pos:'n.'}],
  ['yeah', {meaning:'(非正式)是',pos:'n.'}],
  ['year', {meaning:'年',pos:'n.'}],
  ['yen', {meaning:'日元(日本货币单位)',pos:'n.'}],
  ['yep', {meaning:'是（美国俚语=yes）',pos:'n.'}],
  ['yes', {meaning:'是\nn. 是',pos:'n.'}],
  ['yesterday', {meaning:'昨天\nadv. 昨天',pos:'n.'}],
  ['yet', {meaning:'还',pos:'n.'}],
  ['you', {meaning:'你',pos:'n.'}],
  ['young', {meaning:'年轻的',pos:'n.'}],
  ['your', {meaning:'你的',pos:'n.'}],
  ['yours', {meaning:'你的(东西)',pos:'n.'}],
  ['yourself', {meaning:'你自己',pos:'n.'}],
  ['youth', {meaning:'年轻',pos:'n.'}],
  ['zap', {meaning:'杀死',pos:'n.'}],
  ['zero', {meaning:'零',pos:'n.'}],
  ['zip', {meaning:'尖啸声',pos:'n.'}],
  ['zone', {meaning:'地带',pos:'n.'}],
  ['zoo', {meaning:'动物园',pos:'n.'}],
]);

// ===== 保底词池（用于确保手牌始终有合法单词） =====
// 从2000词中精选500个最高频常用词，按长度分布
const SEED_WORDS = [
  'the',
  'and',
  'for',
  'you',
  'say',
  'but',
  'his',
  'not',
  'she',
  'who',
  'get',
  'her',
  'all',
  'one',
  'out',
  'see',
  'him',
  'now',
  'how',
  'its',
  'our',
  'way',
  'new',
  'day',
  'man',
  'any',
  'try',
  'ask',
  'too',
  'own',
  'put',
  'old',
  'why',
  'let',
  'big',
  'few',
  'run',
  'off',
  'eye',
  'job',
  'far',
  'yes',
  'sit',
  'yet',
  'end',
  'bad',
  'pay',
  'law',
  'car',
  'ago',
  'add',
  'art',
  'war',
  'low',
  'win',
  'air',
  'boy',
  'age',
  'buy',
  'die',
  'cut',
  'son',
  'arm',
  'tax',
  'hit',
  'oil',
  'red',
  'top',
  'cup',
  'act',
  'mrs',
  'fly',
  'bit',
  'aid',
  'sir',
  'use',
  'may',
  'kid',
  'guy',
  'eat',
  'bed',
  'hot',
  'dog',
  'box',
  'lay',
  'sex',
  'gun',
  'leg',
  'sea',
  'bar',
  'bag',
  'gas',
  'nor',
  'key',
  'fan',
  'ice',
  'cry',
  'egg',
  'tie',
  'dry',
  'have',
  'that',
  'with',
  'this',
  'they',
  'from',
  'what',
  'time',
  'year',
  'when',
  'them',
  'some',
  'into',
  'your',
  'come',
  'than',
  'like',
  'then',
  'more',
  'want',
  'look',
  'also',
  'find',
  'here',
  'give',
  'many',
  'only',
  'tell',
  'very',
  'back',
  'good',
  'life',
  'work',
  'call',
  'over',
  'need',
  'feel',
  'high',
  'most',
  'much',
  'keep',
  'same',
  'seem',
  'help',
  'talk',
  'turn',
  'show',
  'such',
  'week',
  'each',
  'hear',
  'play',
  'move',
  'next',
  'must',
  'room',
  'area',
  'fact',
  'book',
  'word',
  'side',
  'head',
  'both',
  'away',
  'hour',
  'game',
  'line',
  'ever',
  'lose',
  'meet',
  'name',
  'once',
  'real',
  'team',
  'idea',
  'body',
  'stop',
  'face',
  'read',
  'door',
  'sure',
  'grow',
  'open',
  'walk',
  'girl',
  'food',
  'foot',
  'able',
  'love',
  'wait',
  'send',
  'stay',
  'fall',
  'plan',
  'kill',
  'care',
  'late',
  'hard',
  'else',
  'pass',
  'sell',
  'role',
  'rate',
  'drug',
  'wife',
  'free',
  'less',
  'hope',
  'view',
  'town',
  'road',
  'full',
  'join',
  'base',
  'star',
  'half',
  'easy',
  'cost',
  'land',
  'wall',
  'news',
  'test',
  'step',
  'draw',
  'film',
  'soon',
  'term',
  'rule',
  'west',
  'seek',
  'past',
  'near',
  'page',
  'race',
  'rise',
  'east',
  'save',
  'fund',
  'sign',
  'list',
  'fail',
  'sort',
  'blue',
  'main',
  'firm',
  'wide',
  'fear',
  'beat',
  'vote',
  'club',
  'their',
  'would',
  'about',
  'there',
  'think',
  'which',
  'could',
  'other',
  'first',
  'thing',
  'woman',
  'child',
  'after',
  'world',
  'still',
  'state',
  'never',
  'leave',
  'great',
  'group',
  'begin',
  'where',
  'every',
  'start',
  'again',
  'small',
  'night',
  'point',
  'today',
  'bring',
  'large',
  'under',
  'water',
  'write',
  'money',
  'story',
  'young',
  'month',
  'study',
  'issue',
  'black',
  'house',
  'since',
  'until',
  'power',
  'often',
  'among',
  'stand',
  'later',
  'white',
  'least',
  'learn',
  'speak',
  'level',
  'allow',
  'spend',
  'party',
  'early',
  'force',
  'offer',
  'music',
  'human',
  'sense',
  'build',
  'reach',
  'local',
  'class',
  'raise',
  'major',
  'along',
  'whole',
  'price',
  'carry',
  'drive',
  'break',
  'thank',
  'value',
  'agree',
  'paper',
  'event',
  'whose',
  'cover',
  'quite',
  'clear',
  'cause',
  'plant',
  'fight',
  'share',
  'stock',
  'staff',
  'trade',
  'stage',
  'laugh',
  'claim',
  'final',
  'green',
  'radio',
  'visit',
  'peace',
  'total',
  'front',
  'press',
  'quick',
  'pound',
  'twice',
  'chief',
  'union',
  'brown',
  'match',
  'while',
  'maybe',
  'serve',
  'death',
  'field',
  'heart',
  'voice',
  'model',
  'space',
  'table',
  'teach',
  'image',
  'phone',
  'piece',
  'movie',
  'north',
  'people',
  'should',
  'school',
  'become',
  'really',
  'family',
  'system',
  'during',
  'number',
  'always',
  'happen',
  'before',
  'mother',
  'though',
  'little',
  'around',
  'friend',
  'father',
  'member',
  'almost',
  'change',
  'social',
  'follow',
  'parent',
  'create',
  'public',
  'office',
  'health',
  'person',
  'within',
  'result',
  'reason',
  'moment',
  'enough',
  'across',
  'second',
  'policy',
  'appear',
  'market',
  'expect',
  'nation',
  'course',
  'behind',
  'remain',
  'effect',
  'former',
  'report',
  'better',
  'effort',
  'decide',
  'strong',
  'leader',
  'police',
  'return',
  'action',
  'season',
  'player',
  'record',
  'ground',
  'matter',
  'figure',
  'street',
  'itself',
  'either',
  'recent',
  'worker',
  'chance',
  'likely',
  'letter',
  'single',
  'future',
  'accept',
  'answer',
  'attack',
  'sister',
  'because',
  'through',
  'between',
  'something',
  'another',
  'student',
  'country',
  'problem',
  'against',
  'company',
  'question',
  'believe',
  'without',
  'national',
  'different',
  'business',
  'provide',
  'service',
  'important',
  'political',
  'however',
  'include',
  'continue',
  'community',
  'president',
  'several',
  'nothing',
  'whether',
  'together',
  'anything',
  'already',
  'history',
  'morning',
  'research',
  'himself',
  'education',
  'although',
  'remember',
  'process',
  'including',
  'consider',
  'actually',
  'probably',
  'interest',
  'suggest',
  'control',
  'perhaps',
  'economic',
  'possible',
  'military',
];

module.exports = { WORD_DATA, SEED_WORDS };
